### ISSUE TITLE
<leader><leader> bindings display with '\'

### ISSUE THREAD

**Issue by z0rc** [liuchengxu/vim-which-key#10]
Hey, I'm exited to see that leader-guide ideas live on with your project, nice work.

I'm curious whether vim-which-key solves issue I have with vim-leader-guide. See https://github.com/hecal3/vim-leader-guide/issues/29#issuecomment-330838188

Short version, I'm using default leader `\` and [easymotion](https://github.com/easymotion/vim-easymotion), that by default uses `<leader><leader>` as prefix for  commands (like `<leader><leader>f`) and I find it quite handy. leader-guide has issues when trying to add definition to these bindings. Is vim-which-key able to handle this case?

**Comment by liuchengxu** [comment]
Seemingly not yet :(, but I'd love to spare some time later to find a workaround. Could you provide a minimal vimrc, current actual and expected behavior for the convenience of anyone interested in this issue?

**Comment by z0rc** [comment]
Actually got it working with which-key with following sample:
```
let g:which_key_map['\']={                                                                                                                                                             
      \ 'name' : 'Easymotion',
      \ 'f' : ['<Plug>(easymotion-f)', 'Find char to the right']
      \ }
It properly registers the mapping and displays notation.

I'm closing this issue as resoled. Thanks again for awesome plugin!

**Comment by LeonardMorgan** [comment]
This is my workaround solution for the problem with <leader><leader> bindings display with ‘\<space>’. I am posting this in case someone needs it. In my case I’m using ’space’ as a leader. I'm pretty sure that it works with almost any other leader character.

let g:which_key_map[' '] = {
      \ 'name' : '+Easymotion ' ,
      \ 'f' : ['<plug>(easymotion-prefix)f' , 'find {char} to the right'],
      \ 'F' : ['<plug>(easymotion-prefix)F' , 'find {char} to the left'],
      \ 't' : ['<plug>(easymotion-prefix)t' , 'till before the {char} to the right'],
      \ 'T' : ['<plug>(easymotion-prefix)T' , 'till after the {char} to the left'],
      \ 'w' : ['<plug>(easymotion-prefix)w' , 'beginning of word forward'],
      \ 'W' : ['<plug>(easymotion-prefix)W' , 'beginning of Word forward'],
      \ 'b' : ['<plug>(easymotion-prefix)b' , 'beginning of word backward'],
      \ 'B' : ['<plug>(easymotion-prefix)B' , 'beginning of Word backward'],
      \ 'e' : ['<plug>(easymotion-prefix)e' , 'end of word forward'],
      \ 'E' : ['<plug>(easymotion-prefix)E' , 'end of Word forward'],
      \ 'g' : {
        \ 'name' : '+Backwards ' ,
        \ 'e' : ['<plug>(easymotion-prefix)ge' , 'end of word backward'],
        \ 'E' : ['<plug>(easymotion-prefix)gE' , 'end of Word backward'],
        \ },
      \ 'j' : ['<plug>(easymotion-prefix)j' , 'line downward'],
      \ 'k' : ['<plug>(easymotion-prefix)k' , 'line upward'],
      \ 'n' : ['<plug>(easymotion-prefix)n' , 'jump to latest "/" or "?" forward'],
      \ 'N' : ['<plug>(easymotion-prefix)N' , 'jump to latest "/" or "?" backward.'],
      \ 's' : ['<plug>(easymotion-prefix)s' , 'find(search) {char} forward and backward.'],
      \ }

<img width="1280" alt="screen shot 2018-10-24 at 2 03 20 pm" src="https://user-images.githubusercontent.com/15827965/47451376-95e96500-d795-11e8-8030-3d6a2b2be6f1.png">
