### ISSUE TITLE
which-key window does not occupy the full width with `signcolume=yes:2` on Neovim

### ISSUE THREAD

**Issue by brglng** [liuchengxu/vim-which-key#100]
**Environment (please complete the following information):**
 - OS: macOS 10.14
 - (Neo)Vim version: NVIM v0.5.0-nightly-1012-g68de6b17b
 - vim-which-key version: c313fc1765df0597be0ebf0129814f0cabf7a55d
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
![图片](https://user-images.githubusercontent.com/1525226/75106428-7eefa700-5657-11ea-8a87-59bea596fb7b.png)

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-which-key
syntax on
filetype plugin indent on
set signcolumn=yes:2
set timeoutlen=300
let g:which_key_use_floating_win = 1
let g:mapleader = "\<Space>"
silent! call which_key#register('<Space>', "g:which_key_map")
nnoremap <silent> <Leader> :<C-u>WhichKey '<Space>'<CR>
vnoremap <silent> <Leader> :<C-u>WhichKeyVisual '<Space>'<CR>
```

2. Start neovim with command: `nvim -u min.vim`

3. Type <kbd>Space</kbd>

**Expected behavior**
which-key window should occupy the full width.

**Comment by liuchengxu** [comment]
That's intentional, https://github.com/liuchengxu/vim-which-key/blob/master/autoload/which_key/window.vim#L50-L52.

**Comment by brglng** [comment]
@liuchengxu How can I configure it to occupy the full width?

**Comment by liuchengxu** [comment]
I can accept PR that adds an option for configuring this behaviour.

**Comment by Akin909** [comment]
I've tried the new option provided and this issue still seems to persist :thinking:. The floating window still seems to leave space equivalent to the signcolumn size to the left. This is whilst using `signcolumn=yes:2`
