### ISSUE TITLE
Does not show keybindings well with custom prefix

### ISSUE THREAD

**Issue by yutakatay** [liuchengxu/vim-which-key#102]
**Environment (please complete the following information):**
 - OS: ArchLinux
 - (Neo)Vim version: Neovim v0.5.0-404-g49cd750d6
 - vim-which-key version: 8f6f4b8efe5f87b26bd89e56b4de6e2a3beee270
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**

I want to use a unite style prefix mapping. 

```vim
nnoremap    [unite]   <Nop>
nmap    s [unite]
```

https://github.com/Shougo/unite.vim/blob/master/doc/unite.txt#L194

But it does not shows keybindings.

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-which-key
syntax on
filetype plugin indent on

nnoremap    [unite]   <Nop>
nmap    s [unite]

nnoremap <silent> [unite]b  :<C-u>buffers<CR>
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type ':WhichKey '[unite]''

**Actual behavior**
```
[ → +prefix

[unite]-
```

**Expected behavior**
```
b → buffers

[unite>]
```

**Additional context**

I used below config instead of `[unite]`. It is work.

```vim
nnoremap <silent> <unite>b  :<C-u>buffers<CR>
```

**Comment by liuchengxu** [comment]
which-key can't be aware of it if that mapping does not appear in `:map`, https://github.com/liuchengxu/vim-which-key/blob/45502b9d28/autoload/which_key/mappings.vim#L30. PR welcome if you have time to look into  this issue.
