### ISSUE TITLE
UI bug in >0.4.0 

### ISSUE THREAD

**Issue by ChristianChiarulli** [liuchengxu/vim-which-key#108]
Seems like since neovim 0.4.0 the UI got a little messed up

It should look like this using 0.3.8:

![image](https://user-images.githubusercontent.com/29136904/78085536-3e3b2a00-7389-11ea-91c2-f91651b58761.png)

but it looks like this using 0.4.3:

![image](https://user-images.githubusercontent.com/29136904/78085672-a1c55780-7389-11ea-814d-f5d50a5f36ec.png)

**Comment by liuchengxu** [comment]
Disable the floating win feature if you don't like it,`g:which_key_use_floating_win = 0`
