### ISSUE TITLE
Which Key hitting `ttimeoutlen` interferes with `toop` bindings

### ISSUE THREAD

**Issue by adiron** [liuchengxu/vim-which-key#11]
I have [`toop`](https://github.com/jeanCarloMachado/vim-toop) set up in my config to do various tasks.

For example:
    call toop#mapFunction('ToCamelCase', '<leader>tc')

Unfortunately, if I'm too slow in hitting `<leader>tciW` for example, which key's menu coming up will interrupt `toop`.

Is there any way to solve this?

**Comment by liuchengxu** [comment]
That's how it works. If you don't complete during the timeoutlen duration the which key window will pop up. I don't think it's a good choice to have such a long key mapping, even in [space-vim](https://github.com/liuchengxu/space-vim) there is no mapping longer than 3 press key (`<leader>**`). I suggest remapping `<leader>tciW` to a shorter one, or you can define a new item in `g:which_key_map`(see README).

**Comment by adiron** [comment]
Sorry, I wasn't clear in my original comment.

I have `toop` mapped at `<leader>tc` for converting text to camel case:

    call toop#mapFunction('ToCamelCase', '<leader>tc')

(as well as a few others)

The problem is that the menu comes up after `<leader>t`, and pressing `c` is dropping me back into normal mode and preventing me from entering the text object I want (such as `iw` or `j` or `W` etc.)

**Comment by liuchengxu** [comment]
Please provide a minimal vimrc and exact steps to reproduce, I am not familiar with toop.

**Comment by adiron** [comment]
Minimum reproducible `.vimrc` (assuming `vim-plug`):

```
call plug#begin()
Plug 'liuchengxu/vim-which-key'
Plug 'jeanCarloMachado/vim-toop'
call plug#end()

set timeoutlen=500

function! ToCamelCase(s) 
    let subbed = substitute(a:s, "\\(\\L\\+\\)", " \\L\\1", "g")
    let sp = split(subbed, "[ _-]\\+")
    let tail = join(sp, " ")

    return substitute(tail, " \\(\\a\\)", "\\u\\1", "g")
endfunction

call toop#mapFunction('ToCamelCase', '<leader>tc')

let g:which_key_map = {}
let g:which_key_map.t = {
            \'name' : 'Transforms',
            \'c' : ['', 'camelCase'],
            \ }

call which_key#register('\\', "g:which_key_map")
nnoremap <silent> <leader> :<c-u>WhichKey '\\'<CR>
vnoremap <silent> <leader> :<c-u>WhichKeyVisual '\\'<CR>

```

**Comment by liuchengxu** [comment]
I have changed a little bit of your provided vimrc, it seemingly works on the latest master. Can you try it again?

```vim
runtime! defaults.vim

call plug#begin()
Plug 'liuchengxu/vim-which-key'
Plug 'jeanCarloMachado/vim-toop'
call plug#end()

set timeoutlen=500

let g:mapleader = ' '

function! ToCamelCase(s)
    let subbed = substitute(a:s, "\\(\\L\\+\\)", " \\L\\1", "g")
    let sp = split(subbed, "[ _-]\\+")
    let tail = join(sp, " ")

    return substitute(tail, " \\(\\a\\)", "\\u\\1", "g")
endfunction

call toop#mapFunction('ToCamelCase', '<leader>tc')

let g:which_key_map = {}
let g:which_key_map.t = {
            \'name' : 'Transforms',
            \'c' : ['', 'camelCase'],
            \ }

call which_key#register('\<Space>', "g:which_key_map")
nnoremap <silent> <leader> :<c-u>WhichKey '<Space>'<CR>
vnoremap <silent> <leader> :<c-u>WhichKeyVisual '<Space>'<CR>
```

**Comment by adiron** [comment]
Hey there!

Sorry for the long delay. I tried it and it works. Apparently I made a bit
of a mistake in my reproduction config. But turns out that the error in my
own rc was a missing backslash. The following diff appears to have solved
my issue:

-call which_key#register('<Space>', "g:which_key_map")
+call which_key#register('\<Space>', "g:which_key_map")

**Comment by liuchengxu** [comment]
Hmm, I don't think so. `call which_key#register('<Space>', "g:which_key_map")` is right, if you use `call which_key#register('\<Space>', "g:which_key_map")`, some other functionalities can be broken.
