### ISSUE TITLE
Error `Unknown function: which_key#window#show`

### ISSUE THREAD

**Issue by BaksiLi** [liuchengxu/vim-which-key#112]
**Environment (please complete the following information):**
 - OS: macOS
 - (Neo)Vim version: Vim 8.2
 - vim-which-key version: latest
 - Have you reproduced with a minimal vimrc: Yes

**Describe the bug**
I have configured my dotfile as instructed in the [minimal-vimrc](https://github.com/liuchengxu/vim-which-key/wiki/mimimal-vimrc), except that I am using `\` as the leader key.
The error is raised when WhichKey is triggered.

```
Error detected while processing function which_key#start:
line   49:
E117: Unknown function: which_key#window#show
```

I have tried to call `call which_key#register('\', 'g:which_key_map')` manually but it doesn't help.

However, this problem can be bodged by sourcing the dotfile again (`source $MYVIMRC`), or by calling `PlugInstall` again. 

**To Reproduce**

```vim
  let g:mapleader = '\'

  let g:which_key_map = {}
  let g:which_key_use_floating_win = 1

  call which_key#register('\', 'g:which_key_map')

  nnoremap <silent> <leader> :<c-u>WhichKey '\'<CR>
  vnoremap <silent> <leader> :<c-u>WhichKey '\'<CR>
```

**Screenshots**
<img width="1069" alt="Screenshot 2020-05-03 at 07 25 48" src="https://user-images.githubusercontent.com/26314680/80907468-6236b600-8d0f-11ea-84ab-b9e4af98552e.png">

**Additional context**
Thank you very much. WhichKey is an exciting plugin, but this problem has been annoying.

**Comment by liuchengxu** [comment]
The minimal vimrc works for me, it's not an issue of vim-which-key itself, you should check your local environment to install a plugin correctly.

**Comment by BaksiLi** [comment]
Just to remind those who have the same problem.

I tried my dotfile on Linux and it worked as expected, so I went back to macOS and **recompiled the latest version** of Vim. And Bobs your uncle.

This might be caused by an unknown bug in the older version of Vim? But since it works perfectly now, I think you should try the solution.

Thanks to @liuchengxu by the way.
