### ISSUE TITLE
g:which_key_timeout无效的问题

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [liuchengxu/vim-which-key#114]
**Environment (please complete the following information):**
 - OS: MacOS 10.14.6
 - (Neo)Vim version: 0.4.2
 - vim-which-key version: 4b70b44
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
有个issue说这个事情, timeoutlen设置太短, 则像vim-commentary等插件,来不及反应按键,导致不可用,如果timeoutlen设置太长, 按space后弹出whichkey界面的响应时间又太长, 我看那个issue说了单独设置g:which_key_timeout可行, 但是没有结论. 
我目前把timeoutlen设置1s, g:which_key_timeout设置100ms,希望vim-commentary可以正常用, whichkey也可以迅速弹出, 但无效, which key还是按照timeoutlen的值执行的.

**Comment by liuchengxu** [comment]
`g:which_key_timeout` is used for resolving the issues like #3 and #4.
