### ISSUE TITLE
Can I create a mapping that includes the Enter key?

### ISSUE THREAD

**Issue by lifeBalance** [liuchengxu/vim-which-key#115]
I had this mapping that allowed me to switch to the last buffer:
```
nmap <Leader><Enter> <C-^>
```
Can I implement the same mapping in vim-which-key? I tried this without success:
```
let g:which_key_map['<Enter>'] = [ ':buffer#' , 'Toggle last buffer' ]
```

**Comment by liuchengxu** [comment]
You can use `<CR>` now:

```vim
let g:which_key_map['<CR>'] = [ ':buffer#' , 'Toggle last buffer' ]
```

My suggestion is not to use these special keys as I personally don't use them and don't know if current vim-which-key can really work with them.

**Comment by lifeBalance** [comment]
Well, I already tried that combination and it works as long as I type it fast, because as soon as the menu pops up it doesn't work.
Also, **turning off the highlighted** text after a search does not work:
```let g:which_key_map['t'] = {
\ 'name' : '+toggle' ,
\ 'n' : [':set invnumber'         , 'line numbers'],
\ 'N' : [':set invrelativenumber' , 'relative line numbers'],
\ 'h' : [':nohlsearch'            , 'No highlighting'],
\ }
```

**Comment by liuchengxu** [comment]
> as soon as the menu pops up it doesn't work

Works for me.

```vim
nnoremap <leader><CR> :echom 'Test Enter'<CR>
let g:which_key_map['<CR>'] = 'Test Enter'
```

**Comment by lifeBalance** [comment]
What works for you? Printing a message to the Vim/Neovim shell? Sure, that works for me too.
That's not my issue though. Have you tried to reproduce the following?
```
nnoremap <Leader><CR> :buffer#<CR>
let g:which_key_map['<CR>'] = 'Toggle last buffer'
```
If you try, you'll see that once the menu pops up, hitting Enter doesn't switch the buffer ;-)

**Comment by lifeBalance** [comment]
Also, should I create another issue for the ``nohlsearch`` mapping?

**Comment by liuchengxu** [comment]
This also works for me. You should see if you can reproduce with a minimal vimrc, otherwise your vimrc probably be blamed.

```vim
nnoremap <Leader><CR> :buffer#<CR>
let g:which_key_map['<CR>'] = 'Toggle last buffer'
```

>should I create another issue for the nohlsearch mapping?

Feel free to create a new one to track that, I haven't dived into it.

**Comment by lifeBalance** [comment]
I forgot to mention that I get the error:
```
[which-key] <space> ^M is undefined
```
I tried with an empty **init.vim**, and the issue still persists, so a configuration clash is definitely not the issue. I also tried this:

```
let g:which_key_map['<CR>'] = [ ':buffer#' , 'Toggle last buffer' ]
```
To no avail...

**Comment by liuchengxu** [comment]
You are not using the latest version, see https://github.com/liuchengxu/vim-which-key/commit/7f3153e699f9a814a072b37c7c64b46546e76d49.

**Comment by lifeBalance** [comment]
Ok, I **updated** and now I have the opposite problem: When I press my leader key (space) I have to wait until the menu pops up to press Enter and switch to the last buffer.
But if I hit Enter **before** the menu pops up, I get the error `[which-key] <space> ^M is undefined`

**Comment by liuchengxu** [comment]
@lifeBalance Can't reproduce.

**Comment by lifeBalance** [comment]
Yes, you're right, it works now, I had to restart tmux.
