### ISSUE TITLE
Keycode for _ ?

### ISSUE THREAD

**Issue by FreemanX** [liuchengxu/vim-which-key#120]
I installed vim plugin tcomment(tomtom/tcomment_vim) which has some key bindings like <leader>_a <leader>_b. I want to hide anything started with <leader>_ in vim which key.
I've tried 
`let g:which_key_map._ = 'which_key_ignore' `  and 
`let g:which_key_map.['_'] = 'which_key_ignore'`

They don't work...

**Comment by liuchengxu** [comment]
Use `let g:which_key_map['_'] = { 'name': 'which_key_ignore' }`.
