### ISSUE TITLE
Toggle WhichKey by Taping Leader Twice

### ISSUE THREAD

**Issue by suliveevil** [liuchengxu/vim-which-key#123]
Specify a key code to quit is not good enough.
If there be a WhichKeyToggle, that will be very helpful.
And we will be able to drop the timeout setting and lose nothing but save a lot of time..

**Comment by liuchengxu** [comment]
If I understand you correctly, you are saying you want to close the which-key window by inputting the prefix key again. That's not sensible as you are actually binding the related key to some exit code(`:h g:which_key_exit`). If you want this for yourself, just add the related mapping of prefix to exit code.

**Comment by suliveevil** [comment]
Not tap prefix key again, twice.
Twice to Show, twice to Quit.

That will be faster than waiting for the “timeoutlen”.

**Comment by liuchengxu** [comment]
timeout is neccessary for resolve the issues like #3 and #45 

>That will be faster than waiting for the “timeoutlen”.

Set `timeoutlen` to 200ms or 100ms if you feel it's a bit longer. I don't think you can tell the difference between 100ms or 0ms.

**Comment by suliveevil** [comment]
**Wait** is different to **Tap**. But I will try to set a shorter timeout.
 Apple also did a “which-key” on macOS and iPadOS, which is **long press** the <kbd>Command</kbd>.

**Comment by liuchengxu** [comment]
**apple-which-key** is not **vim-which-key** as it doesn't have the problem of #3 and #4 in the context of vim.

**Comment by suliveevil** [comment]
I know it is too simple compared to vim-which-key.
But the action **Tap**  **Hold(long press)**  is universal.

**Comment by liuchengxu** [comment]
Have you read #3 and #4?

**Comment by suliveevil** [comment]
Yeah, I just give up and try to get used to it, just like Apple’s Hold `CMD` key.

**Comment by suliveevil** [comment]
This works!

```viml
nnoremap <silent> <leader> :WhichKey '<Space>'<CR>
let g:which_key_exit = "\<Space>" 
```
