### ISSUE TITLE
Feature request: sort by config file

### ISSUE THREAD

**Issue by zdmgmail** [liuchengxu/vim-which-key#124]
**Is your feature request related to a problem? Please describe.**

Want to sort by the name in config file

**Describe the solution you'd like**

```
" f for fzf
let g:which_key_map.f = {
      \ 'name' : '+fzf',
      \ 'f' : [':Files',    'Files'],
      \ 'F' : [':Filetypes',    'File types'],
      \ 'm' : [':Marks',    'Marks'],
      \ 'M' : [':Maps',     'Normal mode mappings'],
```
always want to show f , F , m , M ....

**Comment by zdmgmail** [comment]
if set

let g:which_key_vertical = 1

it use space more than they need  , can I set it to auto fitt it need ?

**Comment by zdmgmail** [comment]
![a](https://user-images.githubusercontent.com/50515839/83663918-e07ec480-a5fb-11ea-9c2d-7c5a8e488df4.png)

**Comment by liuchengxu** [comment]
> Sort by the order of the defined key.

It's unsupported as you can't sort the Dict by the order of key defined.
