### ISSUE TITLE
which-key command mapping does not seem wait for arguments

### ISSUE THREAD

**Issue by i3d** [liuchengxu/vim-which-key#126]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: macOS 10.15.4
 - (Neo)Vim version: 0.5
 - vim-which-key version: vim-plug + git
 - Have you reproduced with a minimal vimrc: yes.

**Describe the bug**

When mapping a command that takes arguments, which-key wouldn't wait for the input and simply just executed and returned.
e.g 
let g:which_key_map.c = {
        \ 'name' : '+code' ,
        \ 's' : ['searchcc'           , 'search .cc'],
        \ }
the searchcc command takes arguments, but no matter how to specify in which-key mapping, it wouldn't wait for the user input...

However, a simple local nno mapping works perfectly fine...
nno <localleader>cs :searchcc<space>

**To Reproduce**

map a key to a command that takes argment(s).

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-which-key
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type '....'

**Expected behavior**

which-key mapping should work the same way as simple nno mapping, commands with arguments should take <space> as the last argument, probably not <cr>.

**Screenshots**

**Additional context**

**Comment by akshat46** [comment]
I just ran into an issue which I think is same as yours. Mapping to a function seems to be the best workaround. E.g:

Normally `:e <path>` would open the specified file in the current window.  Which-key mapping: 
```vim
let g:which_key_map['e'] = [ ':call o_file()',  'open file' ]

function o_file()
    call inputsave()
    let name = input("File Name: ")
    exec ":e ".name
    call inputrestore()
endfunction
```

**Comment by liuchengxu** [comment]
@akshat46 is right, some commands may not work as expected, then you can wrap it with a user-fined command or function. I have added a note in README example comments.

**Comment by i3d** [comment]
Ah, ok, it needs a function wrap and more important I think is that in the function we could use inputsave/inputrestore pairs to wait for user inputs... Thanks for the tips!
