### ISSUE TITLE
Remove existing keys from mappings

### ISSUE THREAD

**Issue by papeloto** [liuchengxu/vim-which-key#127]
**Is your feature request related to a problem? Please describe.**
I'm using vim-airline shortcuts where I do `<leader> 1` to go to tab number 1. I have this mapped for 9 different tabs to navigate quickly. The problem is that it clutters the popup a lot.

![image](https://user-images.githubusercontent.com/36263538/84081956-3ded8980-a9df-11ea-807b-9a612a4d7ae5.png)

**Describe the solution you'd like**
Maybe there is a way to remove the keys. I've tried to `unlet` them but it gives an error saying that there is no item with key `1` in dictionary `g:which_key_map`.

**Describe alternatives you've considered**
The only thing I accomplished is to rename them.

**Comment by liuchengxu** [comment]
You actually means to hide the entry from which-key windo? REAMDE already mentioned:

>If you wish to hide a mapping from the menu set it's description to 'which_key_ignore'. Useful for instance, to hide a list of [1-9] window swapping mappings. For example the below mapping will not be shown in the menu.
>
>```vim
>nnoremap <leader>1 :1wincmd w<CR>
>let g:which_key_map.1 = 'which_key_ignore'
>```
