### ISSUE TITLE
Use other timer instead of timeout

### ISSUE THREAD

**Issue by papeloto** [liuchengxu/vim-which-key#128]
**Is your feature request related to a problem? Please describe.**
I have the timeout set to 500, so I don't have to rush for plugins like `vim-surround`. The problem is that the popup trigger more to open and it appears to be laggy.

**Describe the solution you'd like**
Open the popup immediately.

**Describe alternatives you've considered**
Maybe we can use another function or simply disable that feature through a flag to simply open it instantly.

**Comment by liuchengxu** [comment]
I don't think it's possible, you have to face the cases like #3 and #4.
