### ISSUE TITLE
Spell check should not apply to popup window

### ISSUE THREAD

**Issue by WhyNotHugo** [liuchengxu/vim-which-key#129]
**Environment (please complete the following information):**
 - OS: ArchLinux
 - (Neo)Vim version: NVIM v0.4.3
 - vim-which-key version: dffbb044f7974bf4615960689a3ff64e63daeab3 (current latest)
 - Have you reproduced with a minimal vimrc: Same behaviour

**Describe the bug**

If spell-checking is on for the current file I'm editing (e.g.: markdown), I also get spell checking in the which-key popup, which doesn't really make sense and just makes things ugly.

**To Reproduce**

1. `:set spell`
2. <kbd>Leader</kbd> (or `:WhichKey ' '` if you're on a clean setup)

**Expected behavior**

The popup should never have spellchecking on.

**Comment by WhyNotHugo** [comment]
```vim
autocmd FileType which_key setlocal nospell
```

Sorry for the noise!

**Comment by WhyNotHugo** [comment]
Actually, maybe this should be the default provided by the plugin? I can't think of any scenario where spell-checking _would_ be desirable here?

**Comment by BrotifyPacha** [comment]
Added PR https://github.com/liuchengxu/vim-which-key/pull/174
