### ISSUE TITLE
Hiding non-active localleader keybinds

### ISSUE THREAD

**Issue by jkbch** [liuchengxu/vim-which-key#134]
I like to bind the localleader and the leader to space. When I hit space I would like for which-key to only show available keybinds and hide localleader keybinds that are not active in the current file. 

For example I would like vimtex keybinds to be hidden in which-key when I am not in a latex file as all my vimtex keybinds are bound to localleader and are only active in a latex file. 

Is it possible to hide non-active localleader keybinds in which-key and only show active localleader keybinds in the pop up menu?

Thank for making such a nice plugin :)

**Comment by liuchengxu** [comment]
I think the answer is no, you can't tell them if you use a same key binding.
