### ISSUE TITLE
Cannot see <Space> mappings

### ISSUE THREAD

**Issue by jandamm** [liuchengxu/vim-which-key#135]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: macOS 10.15.6

 - (Neo)Vim version: nvim 0.4.3

 - vim-which-key version: 4e5bd49

 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
I cannot see a `<Leader><Space>` or `<Leader><Leader>` mapping. 
I cannot use a `<Leader><Tab>` mapping.
All works just fine outside of `vim-which-key` but not when the window is opened.

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-which-key
syntax on
filetype plugin indent on

let g:mapleader = "\<Space>"
nnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>

nmap <Leader><Tab>    :bn<CR>
nmap <Leader><SPACE>  :bp<CR>
"nmap <Leader><Leader> :buffers<CR>
```

2. Start (neo)vim with command: `vim -u NONE min.vim -c 'so %'`

3. Type <Space> and wait for a second.
Then try <Space> or <TAB> again

<Space> doesn't show up. <TAB> shows up but isn't usable.

**Expected behavior**
I would expect both mappings to appear and work.

**Screenshots**
<img width="934" alt="Screen Shot 2020-07-28 at 00 16 17" src="https://user-images.githubusercontent.com/5963139/88597481-90eecf00-d067-11ea-884f-0f1218676750.png">

**Comment by jandamm** [comment]
Got it working:

### TAB
Seems to only work when a keymap is registered:

```vim
call which_key#register('<Space>', 'g:which_key_map')
let g:which_key_map =  {}
```
and it works.

### Space
Must be set as a nmap and as registered
```vim
call which_key#register('<Space>', 'g:which_key_map')
nmap <silent> <Leader><SPACE> :bp<CR>
let g:which_key_map =  { ' ': ['bp', 'title' ]}
```
and it works.

**Comment by jandamm** [comment]
I would still consider (at least) the <TAB> mapping as an issue.

**Comment by sooriravindra** [comment]
Hit this issue today and the workaround was very helpful. Thank you @jandamm
