### ISSUE TITLE
Can't mapping with leader key

### ISSUE THREAD

**Issue by foreverLoveWisdom** [liuchengxu/vim-which-key#143]
- OS: POP 20.04
 - (Neo)Vim version: 0.4.3
 - vim-which-key version: Latest
 - Have you reproduced with a minimal vimrc: Yes

**Describe the bug**
Cant mapping with Leader key. When I hit `,` and wait for Which Key to pop up, nothing is shown.
`nnoremap <silent> <leader> :WhichKey  ','<CR>`
`let mapleader = ","`

However, 
`nnoremap <silent> <Space> :WhichKey '<Space>'<CR>`
This works for me. So, I am not sure why it works for the `space` key but not for my `leader` key.

**Comment by macintacos** [comment]
I'm having this same issue. I'm starting my whole vim configuration over from scratch and this is basically the only thing in my `init.vim` that does not work the way I expect it to (but I'm pretty sure has worked just fine in the past). Did something change recently that make this not work? This almost feels like there's an issue with nvim itself or something...

**Comment by tomofumikitano** [comment]
What happens if you put `let mapleader = ","` line before `nnoremap <silent> <leader> :WhichKey ','<CR>`?

For me, this works.
```
let mapleader=","
nnoremap <silent> <leader> :WhichKey ','<CR>
```
And this doesn't.
```
nnoremap <silent> <leader> :WhichKey ','<CR>
let mapleader=","
```
I'm on regular vim. I don't know the reason for this, but it seems the order does matter.

**Comment by liuchengxu** [comment]
By default your `<leader>` is `\`, not `,`, so you have to redefine `g:mapleader` before you use `<Leader>` in the key mappings.
