### ISSUE TITLE
How to delete unused prefix mappings?

### ISSUE THREAD

**Issue by joe23rep** [liuchengxu/vim-which-key#144]
hi, ive set up my whichkey pretty much the way i want it. added everything to ignore i didnt need, created my own prefixes etc.

the only issue ive now is that i have auto generated +prefix keys. 

for example do i have a prefix key automapped to a. when i open it, it has only one option in it (s- toggle autosave). however- i have the shortcut "as"  already set as single key in my whichkey showing up. 

so it shows up doubled. once as single key and once auto generated by the plugin in a prefix setting. i have that 3 times with different stuff. 

do u know how i can delete them completely? or put them to igonre?

i just want to igonre the auto generated prefix keys. 

when i just ad the letter the prefix key is automapped too in the igonre list i get all kinds of issues. so that doesnt work. 

do u know how i can delete the auto generated prefix keys and everything i can find in these prefix keys?

 (in 2 cases its just one mapping i already have and in the 3rd mapping "_" i have stuff like this: <Plug>TComment_<Leader>_<space> from the tcomment plugin).

thank you

**Comment by liuchengxu** [comment]
I think this can help you.

>
>If you want to hide a group of non-top level mappings, set the name to 'which_key_ignore'. For example,
>
>```
>nnoremap <leader>_a :echom '_a'<CR>
>nnoremap <leader>_b :echom '_b'<CR>
>let g:which_key_map['_'] = { 'name': 'which_key_ignore' }
>```
