### ISSUE TITLE
Possible to search through which_key_map?

### ISSUE THREAD

**Issue by macintacos** [liuchengxu/vim-which-key#146]
I'd really like to be able to have the ability to search through all my keymaps, and execute it on-demand. Similar to `SPC SPC` in Spacemacs. I'm not really sure how one would accomplish this, but it would be really nice if this could be added to this plugin (or perhaps an integration with another plugin?).

**Comment by liuchengxu** [comment]
Most fuzzy finder plugins have this feature, see [vim-clap](https://github.com/liuchengxu/vim-clap)'s `:Clap maps`, [fzf.vim](https://github.com/junegunn/fzf.vim)'s `:Maps`, etc.

**Comment by macintacos** [comment]
That's not really what I'm looking for. I want to be able to search through my existing which-key setup, not all mappings in general. Also, it'd be much nicer to be able to search for the strings that I add as descriptions to the commands in which-key, which are much more user friendly and easy to remember compared to mappings that 9/10 times I don't really know what they do unless I sit and stare at them for a while 🙂

**Comment by liuchengxu** [comment]
Then you should write a clap provider based on `g:which_key_map`, or use fzf's API to search what you really want.
