### ISSUE TITLE
Which-key does not working in a recent compiled vim 8.2 (1-1767)

### ISSUE THREAD

**Issue by ricardoareis** [liuchengxu/vim-which-key#148]
**Environment (please complete the following information):**
 - OS: Macosx 10.15.6

 - (Neo)Vim version: 8.2 (1-1767)
 
 - vim-which-key version: 89644ad

 - Have you reproduced with a minimal vimrc: ??? Yes

**Describe the bug**

After the vim upgrade (2 weeks ago, compiled from source), my which-key configuration (1 year) does not work. I isolated with minimal vimrc, aftertouch the leader key (or other) the popup broke if more than one option in a dictionary was defined.

Outdate mac vim (8.2 with 1-607 (my backup)) keeps working. 

**To Reproduce**

Use the minimal vimrc below.

1. Create minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=.vim/bundles/vim-which-key
syntax on
filetype plugin indent on

set timeoutlen=500
let g:mapleader=","
let g:maplocalleader=" "

nnoremap <silent> <Leader>      :<c-u>WhichKey       ','<CR>
nnoremap <silent> <LocalLeader> :<c-u>WhichKey        '<Space>'<CR>

let g:which_key_leader_map = {}
let g:which_key_localleader_map = {}
nnoremap <silent> <leader>ts :update0<CR>
nnoremap <silent> <leader>tb :update1<CR>
let g:which_key_leader_map.t = {
            \'name': '+Toggle',
            \'s': 'update0',
            \'b': 'update1',
            \}

call which_key#register(',',       'g:which_key_leader_map')
call which_key#register('<Space>', 'g:which_key_localleader_map')
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type '....'

Use `,` as a <Leader>, and them, press `t`

Error detected while processing function which_key#start[49]..which_key#window#show[12]..which_key#wait_for_input[17]..<SNR>8_handle_input[4]..<SNR>8_show_next_level_mappings[4]..wh
ich_key#window#show[2]..which_key#renderer#prepare[2]..<SNR>24_create_rows:
line   12:
E117: Unknown function: 1
E702: Sort compare function failed
Error detected while processing function which_key#start[49]..which_key#window#show[12]..which_key#wait_for_input[17]..<SNR>8_handle_input[4]..<SNR>8_show_next_level_mappings[4]..wh
ich_key#window#show:
line    2:
E714: List required

**Expected behavior**
The popup menu should open, and show the dictionary entries.

**Comment by R0LA1mRifcF8yAkk** [comment]
I have the same issue. Just hours after finally installing and configuring the plugin, it stops working...
