### ISSUE TITLE
When I quit WhichKey, the status line disappear

### ISSUE THREAD

**Issue by applejwjcat** [liuchengxu/vim-which-key#149]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: MacOS

 - (Neo)Vim version: 0.4.1

 - vim-which-key version: 89644ad

 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
I have bond the WhichKey to Space, but when I type Space, and type <Esc> to cancel the operation, I find my status line disappeared. Can you give me some advice?

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-which-key
syntax on
filetype plugin indent on

" Here place the configuration that can cause this issue.
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vim-which-key#hide-statusline If you added this in your vimrc, try to remove it.

**Comment by applejwjcat** [comment]
That‘s the last choice
