### ISSUE TITLE
Mapping <leader><leader>?

### ISSUE THREAD

**Issue by divramod** [liuchengxu/vim-which-key#154]
Hey,

thx for the awesome plugin!!

I like to map <leader><leader>.
I am using space as leader.

I tried 

```
let g:which_key_map['<space>'] = {
  \ 'name' : '+SPACE',
  \ 'r' : [ ':Some'    ,'some'],
  \ }
```

and some other combinations.
Is it possible to map special key like leader and/or space presses at all?

**Comment by liuchengxu** [comment]
You can use `' '` for Space in `g:which_key_map`:

```vim
let g:which_key_map[' '] = {
  \ 'name' : '+SPACE',
  \ 'r' : [ ':Some'    ,'some'],
  \ }
```

It's possible to map these specical keys, but not all of them are supported right now, I'm not a heavy user of specical keys. You might run into issues if you use a lot of specical keys.
```
