### ISSUE TITLE
Show mapping only for localleader

### ISSUE THREAD

**Issue by bobicino** [liuchengxu/vim-which-key#159]
**Is your feature request related to a problem? Please describe.**
I have set `leader` to `<Space>` and `localleader` to `<Space>m`.
I would like to show local mappings only for the buffers for which those mappings exists.
For example I have the following autocommand:
```
autocmd FileType markdown nnoremap <buffer> <localleader>p :MarkdownPreview<CR>
```
I could use the following
```
let g:which_key_map['m']['p'] = 'preview'
```
however, that would show that mapping for every buffer, even not markdown files.

**Describe the solution you'd like**
To be able to show mappings only for specific files

**Comment by liuchengxu** [comment]
Duplicate as #48, but I haven't worked on that for a while.
