### ISSUE TITLE
Space Key is not working with as the leader key 

### ISSUE THREAD

**Issue by terminal-guy** [liuchengxu/vim-which-key#162]
this is what is in my neovim config
**nnoremap <silent>  <leader>         :<c-u>WhichKey '<Space>'<CR>
nnoremap <silent> <localleader>    :<c-u>WhichKey  **','<CR>****

**Comment by liuchengxu** [comment]
See this minimal vimrc https://github.com/liuchengxu/vim-which-key/wiki/mimimal-vimrc if you don't know how to use this plugin after reading the README.

**Comment by terminal-guy** [comment]
> See this minimal vimrc https://github.com/liuchengxu/vim-which-key/wiki/mimimal-vimrc if you don't know how to use this plugin after reading the README.

I used the minimal vimrc it throwing a error that [which-key] <space>     id defined
