### ISSUE TITLE
I used the minimal vimrc it throwing a error that [which-key] < space > id defined

### ISSUE THREAD

**Issue by terminal-guy** [liuchengxu/vim-which-key#163]
I used the minimal vimrc it throwing a error that [which-key] < space > id undefined

i opened a previous issue in the bug report buy you closed it i used the minimal vimrc you gaved me but the it just throws me a error

**Comment by terminal-guy** [comment]
![Screenshot from 2020-11-17 15-40-22](https://user-images.githubusercontent.com/58595594/99376750-5c8b7100-28eb-11eb-9c7c-48b41deebfb5.png)

**Comment by liuchengxu** [comment]
That's expected as you don't have that mapping and don't define it in the dict `g:which_key_map`, please read through the README again.

**Comment by terminal-guy** [comment]
> That's expected as you don't have that mapping and don't define it in the dict `g:which_key_map`, please read through the README and vim doc again.



> That's expected as you don't have that mapping and don't define it in the dict `g:which_key_map`, please read through the README and vim doc again.

which vim doc

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vim-which-key/blob/master/doc/vim-which-key.txt.

**Comment by terminal-guy** [comment]
> https://github.com/liuchengxu/vim-which-key/blob/master/doc/vim-which-key.txt, and `:h vim-which-key`.

thanks i finally got it
