### ISSUE TITLE
Foreground and background colors are swapped for the arrow

### ISSUE THREAD

**Issue by matthis-k** [liuchengxu/vim-which-key#169]
OS: arch
terminal emulater: alacritty
neovim: NVIM v0.5.0-dev+950-g5ce328df4

using the nord theme plugin
[link to whole config](https://github.com/matthis-k/lc/tree/master/home/.config/nvim/lua)

the arrow displays with fg and bg swapped
![image](https://user-images.githubusercontent.com/69082876/102887178-bcc78280-4456-11eb-9769-c4d85f925c6d.png)

**Comment by liuchengxu** [comment]
Override the default `WhichKeySeperator` in your own config.

**Comment by dimascyriaco** [comment]
@matthis-k this seams to how Nord [implemented](https://github.com/arcticicestudio/nord-vim/blob/develop/colors/nord.vim#L383) the `DiffAdded` highlight group:

```viml
s:hi("DiffAdd", s:nord14_gui, s:nord0_gui, s:nord14_term, "NONE", "inverse", "")
```

Note de `inverse` param.

To me it worked fine with:

```viml
highlight default link WhichKeySeperator healthSuccess
```
