### ISSUE TITLE
E716: key not present in dictionary: "0"

### ISSUE THREAD

**Issue by zzw99** [liuchengxu/vim-which-key#172]
- OS: MacOS Catalina

 - (Neo)Vim version: v0.5.0-dev+nightly

 - vim-which-key version: latest according to vim-plug

**Describe the bug**
Whenever I invoke whichkey in VisualLine mode I get this error below - any idea where I could have done wrong? 

![image](https://user-images.githubusercontent.com/62851772/107144709-e2401b00-6934-11eb-9069-070f1fa734b1.png)

**Comment by zzw99** [comment]
Closing issue as just found out that GitGutter is messing with my mappings
Cheers

**Comment by entropitor** [comment]
@zwangz What did you do to solve this?

**Comment by zwangz** [comment]
> @zwangz What did you do to solve this?

It's been a while I can't recall exactly but I suspect I realised it wasn't `vim-which-key`'s problem.

**Comment by ferranmarlet** [comment]
For anyone still wondering, I found out that I was getting this error because in my dictionary I had a repeated mapping. I had assigned some values to "which_key_map.w.s" and later I was using the same key in the dictionary again.
