### ISSUE TITLE
[Feature Request] Enable usage with `notimeout` set

### ISSUE THREAD

**Issue by C-Fergus** [liuchengxu/vim-which-key#175]
**Is your feature request related to a problem? Please describe.**
I don't want to wait to be able to remember what keys I need to press and would prefer to see the guide immediately upon leader-press. To do this currently, `timeout` and `timeoutlen=0` must be set which prevents all non-leader key combinations from being used as they instantly time out, making most of Vim's features unusable.

**Describe the solution you'd like**
If `notimeout` is set, immediately open the guide window upon leader press.

**Describe alternatives you've considered**
1. If `notimeout` is set, wait a period of time specified by a plugin variable before opening the guide window, e.g. `g:notimeout_guide_delay`.
2. The current situation where the plugin is unusable if `notimeout` is set.

**Comment by liuchengxu** [comment]
You can't use this plugin with `set notimeout`, see https://github.com/liuchengxu/vim-which-key#requirement.

**Comment by C-Fergus** [comment]
Yes I am aware you currently can not use it with `notimeout` set, this is a *feature request* to *enable the functionality* described which is not currently offered by the plugin.

**Comment by liuchengxu** [comment]
That's not possible to my knowledge.

**Comment by C-Fergus** [comment]
If `notimeout` is what prevents this, then another alternative could be to also allow global commands to be viewed in the guide window similar to #171.
