### ISSUE TITLE
Cannot map :WhichKey "<BS>"

### ISSUE THREAD

**Issue by Akuseru1** [liuchengxu/vim-which-key#178]
Environment (please complete the following information):

    OS: Linux
    (Neo)Vim version: 0.5
    Have you reproduced with a minimal vimrc: yes

Describe the bug
:WhichKey "<BS>" works when typing it by hand, but mapping it to a key produces message:

    E114: Missing quote ")
    E116: Invalid arguments for function which_key#start

To Reproduce

    Make some mappings with as leader (optional)
    :nnoremap :WhichKey "<BS>"<CR>
    Error shows

Expected behavior
Whichkey should function as it normally does in command mode

**Comment by BrotifyPacha** [comment]
I was able to achieve your goal by escaping "<" and ">":
```
:nnoremap <BS> :WhichKey "\<BS\>"<CR>
```
and then registering some dictionary
```
call which_key#register('\<BS\>', "g:backspace")
```

**Comment by Akuseru1** [comment]
While this does what i wanted
> ```
> :nnoremap <BS> :WhichKey "oof"<CR>
> ```
I prefer this other way you mentioned, which also works.

```
:nnoremap <BS> :WhichKey "\<BS\>"<CR>
```
hope this helps anyone.

**Comment by liuchengxu** [comment]
@BrotifyPacha made a very good point here. I have added this kind of question into FAQ in README so that others can find this easier.
