### ISSUE TITLE
E492: Not an editor command: WhichKey ' '

### ISSUE THREAD

**Issue by al3xandru** [liuchengxu/vim-which-key#18]
- OS: macOS 10.14

- Vim: VIM - Vi IMproved 8.1 (2018 May 18, compiled Aug 14 2018 05:28:49)
macOS version
Included patches: 1-280

If you think it's a bug, please provide a minimal vimrc to reproduce:

```vim
Plugin 'liuchengxu/vim-which-key'
nnoremap <silent> <leader>      :<c-u>WhickKey '<Space>'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey ','<CR>
```

### Problem Description

When click <space> I get the error `E492: Not an editor command: WhichKey ' '`.  Mapping works for localleader.

**Comment by liuchengxu** [comment]
You have a trailing space after `'<Space>'`.
```vim
nnoremap <silent> <leader>      :<c-u>WhickKey '<Space>'<CR>
```

**Comment by al3xandru** [comment]
That's unfortunately just a paste issue here. There's no extra space in my `.vimrc`.

**Comment by al3xandru** [comment]
You mean the complete vimrc? I’ll share a link to it momentarily

**Comment by liuchengxu** [comment]
A minimal vimrc and exact steps I can reproduce.

**Comment by al3xandru** [comment]
I understand.  My `.vimrc` is 1700 lines long and I don't know where to start.

**Comment by liuchengxu** [comment]
Then you have to learn how to debug your vimrc :). This issue is easy to fix, what you need to do is to install and configure it properly. You could try removing all current vim-which-key lines in your vimrc and start from zero if you dont know where to go.

**Comment by al3xandru** [comment]
I also want to clarify:

1.  there were no issue with my vimrc before installing vim-which-key
2.  the 3 lines in the description are the only settings I have for vim-which-key.  

I believe that I double checked the README and these are the right instructions.  Combined with the rest of my vimrc, it looks like the behavior for the leader is not working as expected.

**Comment by liuchengxu** [comment]
I cant help with such little snippets. This issue is all about your personal vimrc not the plugin itself. You can try it with any minimal vimrc and I believe it will work  without this issue.

**Comment by al3xandru** [comment]
It was the Whic*k*Key typo.  Thank you.
