### ISSUE TITLE
Wrapper-plugin for easy setup

### ISSUE THREAD

**Issue by AckslD** [liuchengxu/vim-which-key#181]
Hey! I spent quite some time on some functions to make it easier to setup whichkey in lua, and in particular not having to make dedicated commands for more complex stuff which whichkey cannot handle (mentioned in e.g #126). I think it works pretty nice so in the end I decided to just share it as a [plugin](https://github.com/AckslD/nvim-whichkey-setup.lua) if it's of use for someone else. Also wanted to let @liuchengxu know and see if you'd be interested in integrating something like this or prefer to keep it as a separate plugin. It furthermore makes it easy to work with different keymaps for leader, localleder in both normal and visual mode (mentioned in e.g. #155) using either global or buffer local keymaps.

**Comment by liuchengxu** [comment]
That looks interesting! I think it's better to keep it as a separate plugin, but do feel free to send a PR to add a link and some introductions of your plugin in vim-which-key README.

**Comment by AckslD** [comment]
Sounds good! Sure thing I'll add a PR with an update to the README :)
