### ISSUE TITLE
Doesn't load the names 2

### ISSUE THREAD

**Issue by horseinthesky** [liuchengxu/vim-which-key#185]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: `Ubuntu 20.04 WSL`

 - (Neo)Vim version: `NVIM v0.5.0-dev+1219-g0f187700a`

 - vim-which-key version: `fdadbdc`

 - Have you reproduced with a minimal vimrc: Yes.

**Describe the bug**
I set up some namings for single keys and some `+prefix` but they are not displayed.

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set packpath-=~/.local/share/nvim/site
set runtimepath^=$HOME/.local/share/nvim/site/pack/packer/start/vim-which-key
syntax on
filetype plugin indent on

nnoremap <leader>; :vsplit n<CR>
nnoremap <leader>' :split n<CR>
nnoremap <leader>sc :SClose!<CR>
nnoremap <leader>sd :SDelete!<CR>
nnoremap <leader>sl :SLoad!<CR>
nnoremap <leader>ss :SSave!<CR>

nnoremap <silent> <leader> :silent <c-u> :silent WhichKey '<leader>'<CR>
vnoremap <silent> <leader> :silent <c-u> :silent WhichKeyVisual '<leader>'<CR>

" Create map to add keys to
let g:which_key_map =  {}
" Define a separator
let g:which_key_sep = '→'

" Not a fan of floating windows for this
let g:which_key_use_floating_win = 0

" Change the colors if you want
highlight default link WhichKey          Operator
highlight default link WhichKeySeperator DiffAdded
highlight default link WhichKeyGroup     Identifier
highlight default link WhichKeyDesc      Function

" Hide status line
autocmd! FileType which_key
autocmd  FileType which_key set laststatus=0 noshowmode noruler
  \| autocmd BufLeave <buffer> set laststatus=2 noshowmode ruler

let g:which_key_map["'"] = [ '<C-W>s'                     , 'horizontal split' ]
let g:which_key_map[';'] = [ '<C-W>v'                     , 'vertical split' ]
let g:which_key_map.s = {
  \ 'name' : '+sessions' ,
  \ 'c' : ['SClose!'        , 'session close']        ,
  \ 'd' : ['SDelete!'        , 'session delete']        ,
  \ 'l' : ['SLoad!'        , 'session load']   ,
  \ 's' : ['SSave!'        , 'session save']   ,
\ }

" Register which key map
call which_key#register('<leader>', "g:which_key_map")
```

2. Start (neo)vim with command: `nvim -u min.vim`

3. Press `<leader>`

4. See no names
![image](https://user-images.githubusercontent.com/19948672/113606843-34f63480-9651-11eb-9566-0b916bdb8e4a.png)

**Expected behavior**
I should see names for `'`, `;` and `+sessions` prefix.

**Comment by BrotifyPacha** [comment]
The value you are binding in you WhichKey command does not correspond to what you are registering in which_key#register
```
nnoremap <silent> <leader> :silent <c-u> :silent WhichKey '<leader>'<CR>
call which_key#register('<Space>', "g:which_key_map")
```
Btw you dont have to use literal key code as register alias for your dictionary.
Try this.
```
nnoremap <silent> <leader> :silent <c-u> :silent WhichKey 'leader_tree'<CR>
call which_key#register('leader_tree', "g:which_key_map")
```

**Comment by horseinthesky** [comment]
@BrotifyPacha I've fixed the match issue but it is actually no the case.
Don't know why (it is not mentioned anywhere) buy your second point made it to work: using `<leader>` in both `nnoremap` and `call` commands doesn't work any other key does.

Could you pls explain why is that so?

**Comment by liuchengxu** [comment]
By default the leader key is `\`, thus `nnoremap <leader>; :vsplit n<CR>` will be actually mapped to `nnoremap \; :vsplit n<CR>` if you don't override the default one, check that via `:map` for yourself. When you merely press `\`, only the explicit key mappings will be retrieved by vim-which-key as you registered `<leader>` but not `\`.  Try `:WhichKey '<leader>'` directly, you'll see everything is fine, you just don't pull the trigger properly.
