### ISSUE TITLE
Not newb-friendly

### ISSUE THREAD

**Issue by Amparose** [liuchengxu/vim-which-key#186]
**Environment (please complete the following information):**
 - OS: MacOS 11.2.3

 - (Neo)Vim version: Vim 8.2.2725

 - vim-which-key version: fdadbdc

 - Have you reproduced with a minimal vimrc: Yep

**Describe the bug**
Vanilla Vim installing just vim-which-key via Plug. Followed the instructions and when I press space I get:

<img width="690" alt="image" src="https://user-images.githubusercontent.com/949192/114308911-b03e6700-9ae5-11eb-918e-8c7a4e82aea6.png">

Nothing shows and I have no idea where to go from here. The readme indicates that without further settings I should be seeing a list of commands.

**To Reproduce**

My vimrc has:

```vim
set nocompatible
set autoread
set autoindent
set modelines=0 
syntax on
let mapleader = "\<Space>"
let maplocalleader = ','
nnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey  ','<CR>
```

Open vim and press space. Wait and nothing expected shows.

**Comment by ReneganRonin** [comment]
`let g:mapleader = "\<Space>"` and `"let g:maplocalleader=","`
you forgot `g:`

**Comment by Amparose** [comment]
Rah, what a stupid mistake. Thanks for pointing it out.

I am having trouble with dictionaries when the parent key has a mapping along with its children:

```vim
nnoremap <leader>nn :NERDTreeFocus<CR>
map <leader>n :NERDTreeToggle<cr>
map <leader>nb :NERDTreeFromBookmark<Space>
map <leader>nf :NERDTreeFind<cr>

let g:which_key_map.n = { 'name' : '+NERDTree' }
let g:which_key_map.n.b = 'Blahblah'
```

The WhichKey label is still `:NERDTreeFromBookmark<Space>` instead of `Blahblah`.

**Comment by ReneganRonin** [comment]
`let g:which_key_map.n.b = { 'name': 'Blahblah' }`?
should it just be better to follow the example too in the README? dude...

**Comment by Amparose** [comment]
Thanks @ReneganRonin, that worked and I understand better how to configure WhichKey now.

> This issue is weird. This is suppose to be used to report some bugs or feature lol.

Yeah probably, but my argument is the "bug" is the documentation not being clear. This is the first vim plug that I have struggled with this much to configure. Anyway, you helped a lot so sorry for the bother.
