### ISSUE TITLE
How `which_key_use_floating_win' works?

### ISSUE THREAD

**Issue by srustamo** [liuchengxu/vim-which-key#202]
I try to set it to `1` but can't get popup on vim 8.2 in terminal.

Any docs on its use?

**Comment by rene-descartes2021** [comment]
A guess is that `g:which_key_use_floating_win` has to be set prior to the plugin being loaded. As otherwise `s:use_popup` in `autoload/which-key/window.vim` won't be set.

Documentation is in `:help vim-which-key`.

Re-open if there is still issue.
