### ISSUE TITLE
Allow calling lua functions directly?

### ISSUE THREAD

**Issue by jedahan** [liuchengxu/vim-which-key#205]
It feels weird to have a string that 'execs out' to lua when in a lua config file (supported by neovim).

It would be nicer to allow referencing a lua function directly, instead of having to do 
* `':lua vim.lsp.buf.implementation()<CR>'` to
* `vim.lsp.buf.implementation`

<3

**Comment by rene-descartes2021** [comment]
I think that is a feature request for Neovim to allow referencing a Lua function directly within Vimscript. Not something I see in Neovim's reference manual.

Within your Lua configuration file you could probably write some syntactic sugar using lambda functions in Vimscript and/or Lua. A Vimscript funcref is acceptable by vim-which-key for the first element of the list. e.g.:
```vim
let F = function({a -> eval('v:lua.'.a.'()')})
let g:which_key_map.b = [F('vim.lsp.buf.implementation'), 'vim-lsp-buf']
let g:which_key_map.j = [F('vim.lsp.jargon.implementation'), 'vim-lsp-jargon']
```

Keep adding the syntactic sugar to get the end result you want in your Lua configuration file, e.g.
```lua
G = function(a,b,c) ... end
G('b', vim.lsp.buf.implementation, 'vim-lsp-buf')
G('j', vim.lsp.jargon.implementation, 'vim-lsp-jargon')
```

Implementation left up to the reader, I don't use Neovim.
