### ISSUE TITLE
突然无法使用

### ISSUE THREAD

**Issue by minrui-hust** [liuchengxu/vim-which-key#207]
_Instructions: Replace the template text and remove irrelevant text (including this line)_
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Environment (please complete the following information):**
 - OS: ubuntu20.04

 - (Neo)Vim version: nvim0.6.0

 - vim-which-key version: 165772f

 - Have you reproduced with a minimal vimrc: not yet

**Describe the bug**
今天起来突然就不好使了，无法弹出菜单，所有映射失效
尝试重新安装nvim 和所有插件，依然无效。
**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-which-key
syntax on
filetype plugin indent on

" Here place the configuration that can cause this issue.
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type '....'

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by minrui-hust** [comment]
同一个机器vim是ok的，
之前我吧.config/nvim move到了别的地方，然后试用了一个别的nvim配置，然后又move回来，结果nvim下which-key 就完全没有反映了。

**Comment by samwhelp** [comment]
關於nvim，一般可能相關的資料夾路徑如下

```
~/.config/nvim
~/.cache/nvim
~/.local/share/nvim
```

也許先清掉後，再試試看是否可以正常執行

可以參考[我的筆記](https://samwhelp.github.io/note-about-nvim/read/case/lvim-tech.html)。

以上提供參考。

:-)

**Comment by minrui-hust** [comment]
删除了~/.local/share/nvim后ok了，应该是我try的另一个配置，用的lua管理包，导致一些冲突
