### ISSUE TITLE
有些时候按太快会截图的错误

### ISSUE THREAD

**Issue by tracyone** [liuchengxu/vim-which-key#21]
<img width="819" alt="screen shot 2018-10-27 at 07 36 52" src="https://user-images.githubusercontent.com/4246425/47596785-58662100-d9bb-11e8-8ba2-09be17334307.png">

**Comment by liuchengxu** [comment]
I never run into this problem. If it still happens, please provide a minimal vimrc to help reproduce.

**Comment by tracyone** [comment]
你这个提交，大大减少了概率，但是我还是复现了一次s:which_key_trigger没有定义的错误

我猜是：which-key状态栏和vim自己状态栏切换的时候容易出现这个问题。
