### ISSUE TITLE
Using lua doesn't seem to work

### ISSUE THREAD

**Issue by Rizhiy** [liuchengxu/vim-which-key#211]
**Environment (please complete the following information):**
 - OS: Ubuntu 20.04

 - (Neo)Vim version:
NVIM v0.6.0
Build type: RelWithDebInfo
LuaJIT 2.1.0-beta3

 - vim-which-key version: 165772f

 - Have you reproduced with a minimal vimrc: Yes

**Describe the bug**
I can't get lua commands to work using which-key.

How do I do it properly?

**To Reproduce**

1. Create the minimal vimrc `min.vim`:

```vim
let g:mapleader = " "
nnoremap <Space> <Nop>

call plug#begin('$HOME/.vim/plugged')
Plug 'liuchengxu/vim-which-key'
nnoremap <silent> <leader> :WhichKey '<leader>'<CR>
Plug 'nvim-lua/plenary.nvim'
Plug 'windwp/nvim-spectre'
call plug#end()

let g:which_key_map = {}
let g:which_key_map["s"] = [":lua require('spectre').open()<CR>", 'Search']
call which_key#register(' ', "g:which_key_map")
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type '\<space\>s'

4. See error "Vim(lua):E5107: Error loading lua [string ":lua"]:1: unexpected symbol near '<'"

**Expected behavior**
Lua should run properly, if I call the same command from vim command line it works.

**Screenshots**

**Additional context**

**Comment by Freed-Wu** [comment]
I also met bug for nvim-treesitter <https://github.com/nvim-treesitter/nvim-treesitter#incremental-selection>

```lua
    incremental_selection = {enable = true,
        keymaps = {
            init_selection = "gnn",
            node_incremental = "grn",
            node_decremental = "grm",
            scope_incremental = "grc",
        },
    },
```

```
n  gnn         *@<Lua function 28>
                 Start selecting nodes with nvim-treesitter
x  g           * :<C-U>WhichKeyVisual 'g'<CR>
n  g           * :<C-U>WhichKey 'g'<CR>
```

```
Error detected while processing function which_key#start[20]..<SNR>78_cache_key[4]..which_key#mappings#parse:
line   19:
E716: Key not present in Dictionary: "rhs])"
E116: Invalid arguments for function call
line   28:
E716: Key not present in Dictionary: "rhs, '<SID>', '<SNR>'.mapd['sid'].'_', 'g')"
E116: Invalid arguments for function substitute
line   36:
E716: Key not present in Dictionary: "display !~# 'WhichKey.*'"
```

**Comment by thisisrandy** [comment]
@Rizhiy The specific error you're seeing is because of the `<CR>`, which is implicit at the end of any command when using `which-key`. However, if we remove it (now `let g:which_key_map["s"] = [':lua require("spectre").open()', 'Search']`), the error changes to

```
Vim(call):E129: Function name required
```

I'm unsure what this is telling us and would also like to know how to call lua functions properly.

**Comment by thisisrandy** [comment]
I was able to get this working via [nvim-whichkey-setup.lua](https://github.com/AckslD/nvim-whichkey-setup.lua). Try the following:

```vim
call plug#begin('~/.local/share/nvim/plugged')
Plug 'liuchengxu/vim-which-key'
Plug 'AckslD/nvim-whichkey-setup.lua'
Plug 'nvim-lua/plenary.nvim'
Plug 'windwp/nvim-spectre'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
call plug#end()

nnoremap <silent> <leader> :WhichKey '<leader>'<CR>
let g:mapleader = " "

lua<<EOF
local wk = require('whichkey_setup')

local keymap = {
    s = {':lua require("spectre").open()<CR>', 'Search'},
    i = {':lua require("nvim-treesitter/incremental_selection").init_selection()<CR>', 'Incremental selection'}
}

wk.register_keymap('leader', keymap)
EOF
```

@Freed-Wu I also included an example of how to start incremental selection.
