### ISSUE TITLE
Request allow to run native mappings

### ISSUE THREAD

**Issue by rmolin88** [liuchengxu/vim-which-key#22]
- OS: unix

- Vim: nvim-3.2

If you think it's a bug, please provide a minimal vimrc to reproduce:

```vim
	Plug 'liuchengxu/vim-which-key'
	nnoremap <silent> <leader> :WhichKey '<Space>'<CR>
	nnoremap <silent> <localleader> :WhichKey 'g'<CR>

```

### Problem Description

I map `<localleader>` to `g`. But I cannot press `gg` because I get `g g is undefined`.

Please allow to run native mappings.

One of the best plugins I've seen in a long time. Thanks!

**Comment by liuchengxu** [comment]
I don't know if that's possible since it can only be aware of the user defined mappings via `:map` at present. Let me know if you have any insight on implementing this.

**Comment by liuchengxu** [comment]
Well, you can't guarantee these input is always valid.

**Comment by rmolin88** [comment]
Hmmm! Excellent point! I need to think about that! It would be great if  there was a way to detect native mappings!

**Comment by rmolin88** [comment]
I think the solution is to just add mappings to make it show up. Its worth the effort for such a great plugin. Thanks
