### ISSUE TITLE
Hide all mappings that do not have a description.

### ISSUE THREAD

**Issue by blasco** [liuchengxu/vim-which-key#220]
Hi, first of all thank you for such an amazing plugin!
I've seen that there is way to hide mappings:

```
let g:which_key_map.1 = 'which_key_ignore'
```

But is there a way to simply hide all mappings that do not have a proper description? 

My current setup is not very useful: 
![image](https://user-images.githubusercontent.com/3214400/185100709-cc43aed6-a52a-49f1-8880-6c228f1d1944.png)

I would like to show only the commands that I've written a description for. Does this make sense or is there a better approach? 

Or is the only solution to write the 'which_key_ignore' for each single mapping

**Comment by rene-descartes2021** [comment]
Fixed by #219 .
