### ISSUE TITLE
Domain name has been sold?

### ISSUE THREAD

**Issue by ianchanning** [liuchengxu/vim-which-key#225]
Hi there, it looks like the domain name has been lost/sold:

![Screenshot from 2022-11-06 20-06-24](https://user-images.githubusercontent.com/233318/200190070-450d966c-8b2b-45d5-bd55-c1065024bdd3.png)

**Comment by rene-descartes2021** [comment]
Looks like that link should be: https://liuchengxu.github.io/vim-which-key/

**Comment by iFrostizz** [comment]
got led to a nsfw website, would be great to switch it asap

**Comment by liuchengxu** [comment]
Thanks for the reminder, updated.
