### ISSUE TITLE
Mason Registry Error

### ISSUE THREAD

**Issue by charles-d-burton** [liuchengxu/vim-which-key#238]
**Environment (please complete the following information):**
 - OS: Pop!OS 22.04

 - Neovim 9.1

Getting this error when I try to install lunar vim stable
Initializing first time setupError detected while processing /home/charles/.local/share/lunarvim/lvim/init.lua:
Unknown registry type "github": "github:mason-org/mason-registry".
[mason] [ERROR 20:50:41] .../lazy/opt/mason.nvim/lua/mason-registry/sources/init.lua:33: Failed to parse registry "\"github:mason-org/mason-registry\"": 'Unknown registry type "github": "github:mason-org/mason-registry".'
Error detected while processing /home/charles/.local/share/lunarvim/lvim/init.lua..User Autocommands for "LazyDone":
Error executing lua callback: ...harles/.local/share/lunarvim/lvim/lua/lvim/lsp/utils.lua:58: attempt to call field 'refresh' (a nil value)
stack traceback:
        ...harles/.local/share/lunarvim/lvim/lua/lvim/lsp/utils.lua:58: in function 'get_supported_servers'
        ...es/.local/share/lunarvim/lvim/lua/lvim/lsp/templates.lua:60: in function 'generate_templates'
        ...charles/.local/share/lunarvim/lvim/lua/lvim/lsp/init.lua:106: in function <...charles/.local/share/lunarvim/lvim/lua/lvim/lsp/init.lua:91>
        [C]: in function 'nvim_exec_autocmds'
        .../lunarvim/site/pack/lazy/opt/lazy.nvim/lua/lazy/init.lua:88: in function 'setup'
        ...es/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:106: in function <...es/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:104>
        [C]: in function 'xpcall'
        ...es/.local/share/lunarvim/lvim/lua/lvim/plugin-loader.lua:104: in function 'load'
        /home/charles/.local/share/lunarvim/lvim/init.lua:17: in main chunk
Lazy setup complete--------------------------------------------------------------------------------
Verifying core plugins
mismatch at [vim-illuminate]: expected [a290727], got [49062ab]
[ERROR]: Unable to verify plugins, make sure to manually run ':Lazy sync' when starting lvim for the first time.

I'm not sure how to reproduce it.  It works to run the installer on my Ubuntu 22.04 machine and there is more or less no difference between that one and this one.  I'm using the same exact installer as well as it's part of my YADM config.

**Comment by liuchengxu** [comment]
You should report to [lunarvim](https://github.com/LunarVim/LunarVim) instead :(.

**Comment by charles-d-burton** [comment]
Hah, sorry.  I wasn't paying attention.
