### ISSUE TITLE
Not all leader mappings picked up from other plugins (lusty)

### ISSUE THREAD

**Issue by srustamo** [liuchengxu/vim-which-key#25]
x86_64-apple-darwin17.7.0

VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 29 2018 04:52:18)

[lusty-explorer](https://github.com/sjbach/lusty) provides a number of leader mappings, but only one of them shows up in which-key (`<leader`> lb). Any idea why?

**Comment by liuchengxu** [comment]
vim-which-key takes mappings from `:map`, what does `:map <leader>lb` say?

**Comment by srustamo** [comment]
Looks like if more than one chars are in the `leader` mapping, only one of them shows up. Here's the full output of `:map <leader>`. Note how I have many `<leader>h` bindings, but only two show up.

![screenshot 2018-12-12 16 30 38](https://user-images.githubusercontent.com/749813/49867180-7680c700-fe2b-11e8-9745-f6aa46951228.png)

**Comment by liuchengxu** [comment]
Have you updated vim-which-key to the latest version?

**Comment by srustamo** [comment]
I should. I have it as a git submodule, so must be an older commit.

**Comment by srustamo** [comment]
Updated to  d326c18 on master, still have this issue. Do you have your minimal .vimrc to check against? Can you you share?

**Comment by srustamo** [comment]
Also, I don't fully understand `+prefix` usage. I have `nmap <leader>l :set list!<CR>`, and if I remove it from my `.vimrc`, I see `l +prefix` in `which-key` window, selecting it shows all leader bindings of `l`.

**Comment by liuchengxu** [comment]
Quick example:

```vim
set nocompatible

call plug#begin()
Plug 'liuchengxu/vim-which-key'
call plug#end()

let g:mapleader="\<Space>"

nnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey  ','<CR>

nnoremap <Leader>1 :echom "THis is one"<cr>

let g:which_key_map = {}

let g:which_key_map.1 = ['echom "This is one"', "One"]

call which_key#register('<Space>', "g:which_key_map")
```

`+prefix` is the default group name, see https://github.com/liuchengxu/vim-which-key/blob/master/plugin/which_key.vim#L21, that means you have a number of mappings leading by `<Leader>l*`. However, if you have a mapping `<Leader>l`, then vim-which-key will display it rhs instead.

**Comment by srustamo** [comment]
Thanks. What is 'rhs'?

**Comment by srustamo** [comment]
Thanks. Can you share the .vimrc section related to which-key, which produces the screenshot you sent [earlier](https://github.com/liuchengxu/vim-which-key/issues/25#issuecomment-446576566)

**Comment by liuchengxu** [comment]
Here is my config https://github.com/liuchengxu/space-vim. I also change the highlight of WhichKeyDesc in the pict:

```vim
highlight WhichKeyDesc ctermfg=68 guifg=#5f87d7
```

**Comment by srustamo** [comment]
> However, if you have a mapping `<Leader>l`, then vim-which-key will display it rhs instead.

I have only this `l` key mapped in my .vimrc:

`nmap <leader>l :set list!<CR>`

lusty explorer provides these:

```
nmap <silent> <Leader>lf :LustyFilesystemExplorer<CR>
  nmap <silent> <Leader>lr :LustyFilesystemExplorerFromHere<CR>
  nmap <silent> <Leader>lb :LustyBufferExplorer<CR>
  nmap <silent> <Leader>lg :LustyBufferGrep<CR>
```

If I understand you, which-key would only show `nmap <leader>l :set list!<CR>` mapping.
But if you look this [screenshot](https://user-images.githubusercontent.com/749813/49866935-eb073600-fe2a-11e8-96d1-2ffbabc02354.png), one of the lusty's `l` mappings is also shown. 

Your .vimrc suggest the use of dictionary for such cases, is it needed for such cases (single letter and same letter in multiple letter combinations, like `l` and `lb`)?

**Comment by liuchengxu** [comment]
Can't help more if you don't provide a reproducible minimal vimrc.

If you have two mappings `<Leader>l` and `<Leader>lb`, when you press `<Leader>l`, I don't know whether you want to trigger `<Leader>l` or in the middle of `<Leader>lb`, see `:h ttimeoutlen`, so I suggest avoid such mappings. Don't map `<Leader>l` when you have `<Leader>l*` mappings.

Read https://github.com/liuchengxu/vim-which-key#configuration please.

**Comment by srustamo** [comment]
I see. So what I see is expected behavior then. Many thanks.

**Comment by liuchengxu** [comment]
Closing then. Feel free to reopen if you still have questions.
