### ISSUE TITLE
annoying message

### ISSUE THREAD

**Issue by tracyone** [liuchengxu/vim-which-key#29]
- OS: ALL

- Vim: ALL

not a bug, press **esc** immediatey after press  **space**  will  show following message

<img width="355" alt="screen shot 2019-01-16 at 21 02 46" src="https://user-images.githubusercontent.com/4246425/51250724-40a6a380-19d2-11e9-8958-d6b39ef1653c.png">

**Comment by liuchengxu** [comment]
What's your proposal then?

**Comment by liuchengxu** [comment]
`<ESC>` is simply ignored on the start now.
