### ISSUE TITLE
Play nicely with keybind combinations that assume timeoutlen > 0

### ISSUE THREAD

**Issue by yaahallo** [liuchengxu/vim-which-key#3]
It seems that once you enter the WhichKey menu it will immediately exit upon hitting the first valid mapping, regardless of if there are additional mappings that are supersets(right term?) of that mapping.

The example that I've run into comes from commentary, which defines 'gc' and 'gcc'.  If I run `:WhichKey ''` its impossible to enter the second binding. As long as I don't open the whichkey menu and I do enter the correct keyset inside of timeoutlen's duration it works fine. But its impossible to reach some keymappings that would otherwise be reachable when calling them through which-key.

I noticed this because I tried setting timeoutlen to 0 and it completely broke some useful mappings.

I think it would be useful to have something like an additional whichkey specific timeout value that would allow it to keep waiting for more keys to satisfy a longer binding even if a shorter binding has already been satisfied.

**Comment by liuchengxu** [comment]
[vim-leader-guide](https://github.com/hecal3/vim-leader-guide) has no issue with the `gcc` case in that it uses `input()` to interact with users. The weakness of `input()` is that it can't respond quickly when you trigger an invalid item IMO. vim-which-key uses `getchar()` to get input from users and is able to give an instant response when your input is invalid. I will see if there are something I can do.

**Comment by liuchengxu** [comment]
@yaahallo Hello, can you try [this branch](https://github.com/liuchengxu/vim-which-key/tree/whichkey-specific-timeout) which I add a specific timeout for vim-which-key. Now it can distinguish groups like `b` and `b1`. By default the timeout introduced in which-key is same with the option `timeoutlen`.

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vim-which-key/commit/3f54404fa67469a74707e755570c3ecbb6944486 should resolve #4 as well, please give it a test.

**Comment by FinallyFinancialFreedom** [comment]
i think you should put this in readme or help doc.

**Comment by FinallyFinancialFreedom** [comment]
i have tried g:which_key_timeout config, but there is not any effects. everything is same before
