### ISSUE TITLE
Vim:E492: Not an editor command: GVgg

### ISSUE THREAD

**Issue by LinArcX** [liuchengxu/vim-which-key#31]
- OS: Arch linux

- Vim: NVIM v0.3.4

### Problem Description

Hi. i use these mapping:
```
let g:which_key_map.g = {
            \ 'name' : '+file' ,
            \ 'c' : ['d'            , 'Cut']     ,
            \ 'o' : ['e $MYVIMRC'   , 'Open vimrc']     ,
            \ 's' : ['w'            , 'Save']    ,
            \ 'x' : ['GVgg'        , 'Select whole file']     ,
            \ }
```
Everything works except when i hit: __leader+g+x__ and it says:
`Vim:E492: Not an editor command: GVgg`
tip: it actually select whole file in normal mode.

**Comment by liuchengxu** [comment]
Thanks for the report! Please pull the latest commit, should be fixed now.

**Comment by FinallyFinancialFreedom** [comment]
> * OS: Arch linux
> * Vim: NVIM v0.3.4
> 
> ### Problem Description
> Hi. i use these mapping:
> 
> ```
> let g:which_key_map.g = {
>             \ 'name' : '+file' ,
>             \ 'c' : ['d'            , 'Cut']     ,
>             \ 'o' : ['e $MYVIMRC'   , 'Open vimrc']     ,
>             \ 's' : ['w'            , 'Save']    ,
>             \ 'x' : ['GVgg'        , 'Select whole file']     ,
>             \ }
> ```
> 
> Everything works except when i hit: **leader+g+x** and it says:
> `Vim:E492: Not an editor command: GVgg`
> tip: it actually select whole file in normal mode.

`'o' : ['e $MYVIMRC'   , 'Open vimrc'] ` doesn't work for me.
