### ISSUE TITLE
Error when using series command

### ISSUE THREAD

**Issue by vuquangtam** [liuchengxu/vim-which-key#33]
- OS: Linux

- Vim: 8.1

```vim
let g:which_key_map.a = {
          \ 'name' : '+apps' ,
~         \ 't' : ['botright terminal' , 'terminal']                        
          \ }

```

### Problem Description

When i use series command like: `botright terminal`, it doesn't invoke the command but instead append the command text to my current buffer

**Comment by liuchengxu** [comment]
Try `':botright terminal\<CR>'`.
