### ISSUE TITLE
有时候键位查找出问题，leader键可以定义map吗？

### ISSUE THREAD

**Issue by taigacute** [liuchengxu/vim-which-key#34]
- OS: mac os 10.13.6

- Vim:  neovim 0.3.5

If you think it's a bug, please provide a minimal vimrc to reproduce:

N/A

### Problem Description

有时候可以检测到`leader+e`有时候检测不到但是我还是可以正常使用，我映射`leader+e` 打开nerdtree，leader的map能定义吗？我使用dein并且懒加载whichkey通过`on_cmd`调用

![whichkey](https://user-images.githubusercontent.com/41671631/52893683-0ea77d80-31da-11e9-9650-f57dde3cabee.gif)

**Comment by liuchengxu** [comment]
vim-which-key 通过两种途径收集 key mapping, 一是用户自定义的 map，这一点你可以通过 `:verbose [n/v]map 你的map` 进行判断，如果返回有内容，vim-which-key 会自动解析到这个 map。二是定义在 register 时传入的 dict 里面。无论哪种途径，只要能够找到这样的 map, vim-which-key 就会展示，你就可以使用。vim-which-key 只是附加的一层，本身不会对你的 key mapping 有任何要求。你的 key mapping 是怎样的，它就会怎么收集并展示。

**Comment by taigacute** [comment]
是有返回内容的，我可以正常使用，但是它有时候解析不到，我在想是不是解析map有问题，因为我的映射是 `map <leader> e nerdtreetoggle` ，是不是解析map有问题需要noremap之类的才会正常呢？dict怎么设置leader 我设置了但是没读取。

**Comment by taigacute** [comment]
@liuchengxu  gitter里说？
