### ISSUE TITLE
what is the use of timeoutlen ? Why setting it to 10 break gcc commentary ? 

### ISSUE THREAD

**Issue by 4vrel** [liuchengxu/vim-which-key#35]
Hello,
Using neovim, with tpope commentary and which-key.
I set up timeoutlen to 10, because 500 was a bit slow, but now it broke gcc mapping from tpope commentary plugin.
I tryed to put it to 300, and now it fells like I have to press gcc in less than 0,3s to make it work.
Can you please explain what is the meaning of timeoutlen and why it has to exist ? 
Coming form spacemacs its seems that both space-menu and gcc could live together without the need of a timeoulen variable.
Thanks for your work !

**Comment by liuchengxu** [comment]
excerpt from `:h timeoutlen`:

```
'timeoutlen' 'tm'	number	(default 1000)
			global
	Time in milliseconds to wait for a mapped sequence to complete.
```

Assuming you have two mappings: `gc` and `gcc`, when you pressed `gc` and stopped, vim would wait `timeoutlen` to see if you want to trigger `gc` or just in the middle of `gcc`.

Also see https://vi.stackexchange.com/questions/3964/timeoutlen-breaks-leader-and-vim-commentary.

**Comment by ayushxx7** [comment]
Thanks. I have been scratching my head for over an hour regarding why which-key is causing problems with [vim-unimparired](https://github.com/tpope/vim-unimpaired) & [vim-commentary](https://github.com/tpope/vim-commentary). Turns out, setting `timeoutlen` to 100ms was causing the problem!
