### ISSUE TITLE
why gitgutter automaticly add binding to my space menu ?

### ISSUE THREAD

**Issue by 4vrel** [liuchengxu/vim-which-key#36]
Hello,
After installing gitgutter with vim-plug,  I was surprised that which_key_map.h was  assign to 'prefix'
and this menu was filled with : 
p → <Plug>GitGutterPreviewHunk     
u → <Plug>GitGutterUndoHunk          
s → <Plug>GitGutterStageHunk         
Where does this mapping come from and how can I edit it ?

**Comment by liuchengxu** [comment]
These mappings are defined by vim-gitgutter, see https://github.com/airblade/vim-gitgutter/blob/2dce8e032b9c1989a41296aaeccc8f17dc83c707/autoload/gitgutter.vim#L123-L131.

vim-which-key would parse these mapping automatically. TO override these auto parsed items by defining them explicitly:

```vim
let g:which_map.h = {
      \ 'name' : '+help',
      \ 'h': [':echom "hello"', 'echo hello']
      \ }
```

**Comment by ironfish** [comment]
@4vrel based on your question, I am assuming you want to hide the Gitgutter stuff? If that is the case, then this will work:

```
let g:which_key_map.h = {'name' : 'which_key_ignore'}
let g:which_key_map.h.p = 'which_key_ignore'
let g:which_key_map.h.s = 'which_key_ignore'
let g:which_key_map.h.u = 'which_key_ignore'
```
