### ISSUE TITLE
Don't flash menu for a split second when running commands defined through key map dictionary

### ISSUE THREAD

**Issue by yaahallo** [liuchengxu/vim-which-key#4]
I noticed that if you define a mapping only through the dictionary, rather than having dual definitions for it, entering the mapping, even if you do it within timeoutlen, will cause the menu to flash open for a split second then close, and then run the command. This super quick flash of the menu is rather disruptive / annoying.

I tried working around this by setting timeoutlen to 0 and just always relying on the expectation that which_key would open immediately, and that felt good except for the fact that it caused https://github.com/liuchengxu/vim-which-key/issues/3

Solving https://github.com/liuchengxu/vim-which-key/issues/2 would let me fix this issue well enough for my satisfaction in that I would make sure all my mappings are defined outside of the key map, and my key map dictionary entries would only contain information about names and aliases, not any actual command definitions.

**Comment by liuchengxu** [comment]
Please [try this branch](https://github.com/liuchengxu/vim-which-key/tree/allow-provide-description-only) which is an attempt to solve #2.

**Comment by yaahallo** [comment]
Seems to work great. I'm a little sad that I cant just do a 1 stop definition in my dict, but at least I only have to add additional naming when the command itself is super long or not obvious what it does.
