### ISSUE TITLE
 listchar display is not normal when trigger whickey

### ISSUE THREAD

**Issue by taigacute** [liuchengxu/vim-which-key#40]
- OS: macos

- Vim: nvim 0.3.4

If you think it's a bug, please provide a minimal vimrc to reproduce:

```vim

```

### Problem Description

触发whichkey之后 listchar的显示不正常。更新了最新的whichkey，之前的版本并没有这个问题。

![go](https://user-images.githubusercontent.com/41671631/54014423-953af380-41b7-11e9-8004-1173534ef103.gif)

**Comment by liuchengxu** [comment]
I can only reproduce under vim, but not the latest neovim(v0.4.0-dev). So I guess it's actually a problem of vim or some older neovim themselves.

**Comment by taigacute** [comment]
thanks a lot，its normal in neovim。
