### ISSUE TITLE
如何映射Ctrl快捷键

### ISSUE THREAD

**Issue by ZMK112** [liuchengxu/vim-which-key#44]
- OS: ubuntu16.04

- Vim: 8.1

请问如何映射Ctrl键呢？我在文档里面没有看到类似的例子。
这样写是错误的。
```
nnoremap <silent> <ctrl> :<c-u>WhichKeyVisual '<ctrl>'<CR>
```

**Comment by liuchengxu** [comment]
没有单独的 Ctrl 键，Ctrl 都是组合键 `<C-...> `，见 `:h ctrl`。

**Comment by ZMK112** [comment]
那岂不是意味着每一个ctrl组合键都需要map到一个whichkey命令？可以这么理解吗？

**Comment by liuchengxu** [comment]
这很没有意义，多用 `<Leader>` 键，见 `:h <Leader>`。[space-vim](https://github.com/liuchengxu/space-vim) 几乎所有快捷键都是通过 `<Leader>` 来组织，既方便记忆，也方便管理。
