### ISSUE TITLE
Feature request: show only mapping with explict description

### ISSUE THREAD

**Issue by free-easy** [liuchengxu/vim-which-key#46]
### Problem Description

I would like to have `which-key` to show only mappings for which I provide a description.
AFAICT it's not possible now.

**Comment by liuchengxu** [comment]
You can hide a mapping by setting its description to `which_key_ignore` if you don't wish to show it:

```vim
nnoremap <leader>1 :1wincmd w<CR>
let g:which_key_map.1 = 'which_key_ignore'
```

It's not a direct way, but still an option to meet your need, so I won't add another way to achieve this my self. I'm also not against another PR for this by the way.
