### ISSUE TITLE
Problem when running on command line vim on Windows

### ISSUE THREAD

**Issue by spapas** [liuchengxu/vim-which-key#5]
Hello, continuing from #2 ,  when I try it in command line vim in Windows, after I press space and a key I see the following error:

```
Error detected while processing BufLeave Auto commands for "<buffer=3>": E464: Ambiguous use of user-defined command: V
```

Using gvim works great.

**Comment by liuchengxu** [comment]
I can reproduce in cmd vim and powershell, but after the error message has been echoed, vim-which-key still works and the message never appears again. Git Bash doesn't have this issue. Will look into this later.

**Comment by spapas** [comment]
Hello @liuchengxu in my case it is not working properly after the error has been echoed. What happens after that error is that whenever I press a key I see a non printable character in insert mode and that printable character and the character in command mode. This is really strange to explain so I'll provide a screenshot:

![err](https://user-images.githubusercontent.com/3911074/45255402-9321e480-b38e-11e8-839f-026907f24959.png)

This is how my vim looks like after I've triggered the error and tried writing "Hello" to both the main buffer and the command prompt!

**Comment by spapas** [comment]
Hello @liuchengxu  after some research I found out that the problem is in file `which_key/window.vim` in the following lines (57):

```
  augroup which_key_cursor
    autocmd!
    execute 'autocmd BufLeave <buffer> set t_ve=' . &t_ve
    execute 'autocmd VimLeave <buffer> set t_ve=' . &t_ve
  augroup END
```

The error is because in windows cmd the `t_ve` has a value of `^[|V` which needs to be escaped. So if you change the execute lines like this it won't throw the error anymore:

```
    execute 'autocmd BufLeave <buffer> set t_ve=' . escape(&t_ve, '|')
    execute 'autocmd VimLeave <buffer> set t_ve=' . escape(&t_ve, '|')
```

If you can confirm that this actually resolves the error I'd be happy to provide a PR!

**Comment by liuchengxu** [comment]
Good, I also just found the root cause! I can confirm your solution works, please open up a PR.
