### ISSUE TITLE
Can I map a key which is not leader key

### ISSUE THREAD

**Issue by IndexXuan** [liuchengxu/vim-which-key#50]
- OS: Mac

- Vim: NeoVim 0.4

If you think it's a bug, please provide a minimal vimrc to reproduce:

```vim

```

### Problem Description

A Great Plugin ! Can I map a key which is not leader key ?
Right now, I map ';' as leader and use well, can I map Space as well, it is a normal key
```vim
 let g:which_key_map = {
     " xxx works well with leader
  }
 let g:which_key_map['<Space>'] = {
    " xxx not work with normal key <Space>
 }
  nnoremap <silent> <leader> :<c-u>WhichKey '<leader>'<CR>
  nnoremap <silent> <Space> :<c-u>WhichKey '<Space>'<CR>
  autocmd! User vim-which-key call which_key#register(g:mapleader, 'g:which_key_map')
```
when I enter 'Space', only native parse of vim, cannot get my description for <Space>
map be the usage of which_key#register ?

**Comment by liuchengxu** [comment]
Use `let g:which_key_map[' '] = {..}` for space key. Th special keys are not well handled and documented. I'm not motivated to _fix_ this part, so it's not recommended to use these special keys.

**Comment by IndexXuan** [comment]
@liuchengxu 
autocmd! User vim-which-key call which_key#register('<Space>', 'g:which_key_map[" "]')
enter space will show native parse info, instead of desc of mine

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/space-vim/blob/master/core/autoload/spacevim/autocmd/which_key.vim#L2

**Comment by IndexXuan** [comment]
@liuchengxu 多谢，理解了，which_key_map 只是个普通 vim 变量，了解了，多谢
