### ISSUE TITLE
[feature request] Backspace back to upper level + don't break at nonexist keymap

### ISSUE THREAD

**Issue by OliverLew** [liuchengxu/vim-which-key#54]
I like what vim-leader-guide does. There are some scenarios where the current behavior might be annoying:
1. just browse through some the keymaps. But currently after going into one dict (e.g. `'<leader>g'`), I don't know how to go directly back (to `'<leader>'`).
2. I typed wrong keys. Currently it will break and show an error message. I think it might be better to do nothing and allow user to delete the wrong key and continue with the desired one.

So the point is change how `<backspace>` key works. Actually now hitting `<backspace>` will change the focus to popup window somehow which does nothing good.

**Comment by liuchengxu** [comment]
Your points makes sense. Try #56 and let me if you run into some error.

**Comment by OliverLew** [comment]
I noticed it started to behave strangely after I typed a invalid key mapping.
1. `<backspace>` works well only when the keys I typed so far are correct.
2. The invalid keys are really simply ignored right now. Even `<backspace>` does not delete them. Typing other invalid keys between a valid key mapping still works.
I am using the latest 'allow-backspace-to-upper-level' branch.

**Comment by liuchengxu** [comment]
There is no `delete` action essentially.

>Typing other invalid keys between a valid key mapping still works.

Can you elaborate?

**Comment by OliverLew** [comment]
> There is no `delete` action essentially. Every single invalid key is ignored since vim-which-key responses to your each input char and doesn't remember your previous input.
> 

But the keys typed are shown down in the command window, sometimes the behavior will be inconsistent.
Suppose I have `<leader>g` sub-dict but don't have `<leader>ga` key mapping. And now do the following steps:
1. Type `<leader>`, a window pops up.
2.  Type `g` will go to the sub-dict as expected.
3. Then type `a`, nothing happens also as expected.
4. Then `<backspace>`, now `a` will be 'deleted' in the prompt (leaves `<leader>g`) and it goes to the upper level dict (as in step 1). In other words, now I am in `<leader>` level, but it shows `<leader>g`.

I think `g` should've been deleted but it was `a` because it was the last letter typed.

> > Typing other invalid keys between a valid key mapping still works.
> 
> Can you elaborate?

Suppose I have `<leader>cc` as a key mapping but no `<leader>z*`. Then if I type `<leader>zcc`, the key mapping of `<leader>cc` will work.

**Comment by liuchengxu** [comment]
> But the keys typed are shown down in the command window, sometimes the behavior will be inconsistent.

Pull the latest commit of #56, should be fixed.

>Suppose I have <leader>cc as a key mapping but no <leader>z*. Then if I type <leader>zcc, the key mapping of <leader>cc will work.

I don't have a solution for this case. You can choose either to popup the error message or ignore the invalid input.

**Comment by OliverLew** [comment]
Yes, blocking the invalid keys has solved all the issues! I think it works perfectly regarding the feature request.

BTW, maybe a irrelevant issue, if I hold on a invalid key for some time, there will be a pile of error messages popping up. The last one is "E132: Function call depth is higher than 'maxfuncdepth'".

**Comment by liuchengxu** [comment]
The `E132` issue you point out is not the normal case and may won't be fixed.
