### ISSUE TITLE
Hide specific mappings

### ISSUE THREAD

**Issue by weilbith** [liuchengxu/vim-which-key#57]
Is it possible to hide some mappings? For example do I use some mappings to jump to a buffer or window by their number. Thereby the which-key window shows each single mapping from 1 to 9 in these cases. I would like to summerize them. The former part already works, as you stated in the README that the entries of the mapping must not actually exist.

**Comment by liuchengxu** [comment]
`'which_key_ignore'` doesn't meet your need?

**Comment by weilbith** [comment]
I'm just blind and can not read...

**Comment by c02y** [comment]
Actually combing 1-9 bindings such as `<Leader> b 1/2/.../9` -> `buffer-1/2/.../9` to a single string in popup window like `<Leader> b 1..9` -> `buffer-1..9`    is better, just like Spacemacs does as the following screenshots.

![spcb](https://user-images.githubusercontent.com/2135996/61283874-63ced600-a7f0-11e9-9c38-37c08e4cfb9b.png)
![spcN](https://user-images.githubusercontent.com/2135996/61283875-64676c80-a7f0-11e9-958a-b2e3ebb6f8d6.png)

**Comment by liuchengxu** [comment]
Feel free to create another issue, but I can't promise when I'll get time to implement that.
