### ISSUE TITLE
highlight with floatwindow

### ISSUE THREAD

**Issue by taigacute** [liuchengxu/vim-which-key#58]
- OS: macos

- Vim: 0.4.0 dev

If you think it's a bug, please provide a minimal vimrc to reproduce:

### Problem Description

i found the floatwindow  highlight of whichkey  is pmenu. so  i cant use this to change highlight
```vim
highlight NormalFloat cterm=NONE ctermfg=14 ctermbg=0 gui=NONE guifg=#93a1a1 guibg=#002931
```
please check here
```VIML
  if exists('&winhighlight')
    setlocal winhighlight=Normal:Pmenu
  endif
```

**Comment by liuchengxu** [comment]
Use `WhichKeyFloating` for customization.

**Comment by taigacute** [comment]
thanks for your work!!
