### ISSUE TITLE
Unable to add description for maps

### ISSUE THREAD

**Issue by c02y** [liuchengxu/vim-which-key#59]
- OS: openSUSE Tumbleweed

- Vim: 8.1

If you think it's a bug, please provide a minimal vimrc to reproduce:

```vim

```

### Problem Description

I'm following the README.md file+https://github.com/liuchengxu/vim-which-key/issues/53 to add description text for maps
using the following lines(I'm using space-vim, so some of them are not actually needed):
~~~
function! UserConfig()
    let g:which_key_map = {}
    autocmd VimEnter * call which_key#register('<Space>', "g:which_key_map")
    nnoremap <silent> <leader> :<c-u>WhichKey '<Space>'<CR>
    vnoremap <silent> <leader> :<c-u>WhichKeyVisual '<Space>'<CR>

   " ...


endfunction

~~~

But the following error message is displayed when I open vim:
~~~
Error detected while processing VimEnter Autocommands for "*":
E117: Unknown function: which_key#register
Press ENTER or type command to continue
~~~

When I add 
~~~
   nnoremap <Leader>ff :Files<CR>
   let g:which_key_map.f.f = 'Files in current dir'

~~~
to add description for a map, the following error message is displayed:
~~~
Error detected while processing function spacevim#bootstrap[2]..spacevim#end[9]..UserConfig:
line   71:
E716: Key not present in Dictionary: f.f = 'Files in current dir'
Press ENTER or type command to continue
~~~

So what should I exactly do to add description for a map?

**Comment by liuchengxu** [comment]
The instructions of vim-which-key is for general vim user, not for space-vim users. You have to know how space-vim integrates vim-which-key. I use the lazy load feature of vim-plug to load vim-which-key in space-vim. You should report to space-vim repo.

**Comment by c02y** [comment]
When I'm using 
~~~
let g:which_key_map = {}
autocmd VimEnter * call which_key#register('<Space>', "g:which_key_map")
nnoremap <silent> <leader> :<c-u>WhichKey '<Space>'<CR>
vnoremap <silent> <leader> :<c-u>WhichKeyVisual '<Space>'<CR>

nnoremap <Leader>ff :Files<CR>
let g:which_key_map.f.f = 'Files in current dir'
~~~
inside my own vimrc, the following error message is still displayed:
~~~
E716: Key not present in Dictionary: f.f = 'Files in current dir'
~~~

So, how should I add description for a map?
