### ISSUE TITLE
Conflict with `<C-w>`(any arrow)

### ISSUE THREAD

**Issue by codehz** [liuchengxu/vim-which-key#67]
- OS: linux

- Vim: NVIM v0.4.2

If you think it's a bug, please provide a minimal vimrc to reproduce:

```vim
let g:mapleader = "\<Space>"
nnoremap <silent> <Leader> :WhichKey '<Space>'<CR>
nnoremap <silent> <Space><Up> <C-w><Up>
```

### Problem Description
Using above vimrc and press space (wait 1s), and then press `<up>` key
Or even just press `<C-w><Up>` when the popup menu showing

PS:
I can even use visual mode in this tab(if let g:which_key_use_floating_win = 0)
![image](https://user-images.githubusercontent.com/13158903/65375131-a1eee700-dcc4-11e9-98fb-0373ff4f43ad.png)

**Comment by liuchengxu** [comment]
I haven't looked into this problem(_maybe never_ ). But I believe you can easily find a workaround: use `wincmd` instead of `Ctrl-W`, `:h wincmd`.

**Comment by codehz** [comment]
ok, the workaround is working.
