### ISSUE TITLE
allow a user defined escape key

### ISSUE THREAD

**Issue by MoHKale** [liuchengxu/vim-which-key#68]
- OS: WSL ubuntu (bash on windows)

- Vim: Nvim v 0.3.7

### Problem Description

I'd like to ask for an option to add a user defined escape key. A character of 27 (the unicode equivalent of escape) is hardcoded into use [here](https://github.com/liuchengxu/vim-which-key/blob/master/autoload/which_key.vim#L43) and [here](https://github.com/liuchengxu/vim-which-key/blob/master/autoload/which_key.vim#L170). I'd like a new optional variable which if not null, is also checked alongside escape. In my case, I'd like it to be `Ctrl-g`. that's the same key I use as an alias for escape in most other modes & having to use escape to exit which-key breaks my flow. I believe some users also rebind `TAB` to escape so this could also be useful for them. This shouldn't be too big of a change, thoughts?

**Comment by liuchengxu** [comment]
That's reasonable.

**Comment by liuchengxu** [comment]
See if #69 works for you.

```vim
let g:which_key_exit = "\<C-G>"
```

**Comment by MoHKale** [comment]
```
let g:which_key_exit = "\<C-G>"
```

is working 😄. but the multi option variant doesn't seem to be. `let g:which_key_exit = [27]` throws an error for me:

```Error detected while processing function which_key#start[54]..which_key#window#open[31]..which_key#window#fill[24]..which_key#wait_for_input[17]..<SNR>15_handle_input[16]..which_key#wait_for_input[17]..<SNR>15_handle_input[16]..which_key#wait_for_input[17]..<SNR>15_handle_input[16]..which_key#wait_for_input[17]..<SNR>15_handle_input[16]..which_key#wait_for_input[10]..<SNR>15_getchar[11]..<SNR>15_is_exit_code:
line 6:
E15: Invalid Type Expression: ty = s:TYPE.list
```

I had to transcribe that last line by hand, it kept disappearing too quickly.

**Comment by liuchengxu** [comment]
@MoHKale Fixed :(.

**Comment by MoHKale** [comment]
kay, this is great. no problems on my end. `let g:which_key_exit = [27, 7]` binds both escape and `Ctrl-g` to quit which-key. Thnx for the quick response and the stellar work 😄.
