### ISSUE TITLE
Feature Request: View output categorized by mode

### ISSUE THREAD

**Issue by windowsrefund** [liuchengxu/vim-which-key#74]
### Suggestion

It would be nice if it were easy to determine what mode a binding was set for.

This example output show 3 configured bindings; 2 are set using nnoremap while 1 is set with inoremap. As we can see, it's not possible to understand at a glance which binding will only work when used in insert mode.

```
a -> foo
b -> bar
c -> baz

\-
```

**Comment by liuchengxu** [comment]
Technically it's trivial to get the mode info of each mapping, but I'm not motivated to implement it by myself unless you have a clear design, e.g., where to put the mode info.
