### ISSUE TITLE
Feature Request: support non leader key prefix

### ISSUE THREAD

**Issue by stephencheng** [liuchengxu/vim-which-key#75]
Is it possible that vim-which-key can support showing non leader key mappings?

For example, if I have:

bl -> list buffer
bn -> buffer next
bp -> buffer previous

When I type b, it will give me the prompt of these 3 entires.

I understand that this could be very annoy because it will probably need to monitor every key. Or if this is supported, can we make it less disturbing to at least showing it in the status bar, so that I can get the feedback of the mappings?

**Comment by liuchengxu** [comment]
Try `nnoremap <silent> b :<c-u>WhichKey 'b'<CR>`.
