### ISSUE TITLE
How to customize the background color of the empty area

### ISSUE THREAD

**Issue by schfkt** [liuchengxu/vim-which-key#76]
I was able to customize almost all of the colors for vim-which-key window like this:

```
autocmd FileType which_key highlight WhichKey ctermbg=12 ctermfg=7
autocmd FileType which_key highlight WhichKeySeperator ctermbg=12 ctermfg=7
autocmd FileType which_key highlight WhichKeyGroup cterm=bold ctermbg=12 ctermfg=7
autocmd FileType which_key highlight WhichKeyDesc ctermbg=12 ctermfg=7
```

But, there's an empty area left around the blocks (the dark grey one):

<img width="695" alt="image" src="https://user-images.githubusercontent.com/3599143/66673661-afffaa00-ec69-11e9-800e-a016e4df5283.png">

How can I change the color for that area? I've checked the source code of the plugin, but couldn't find anything. Thanks for your help!

**Comment by liuchengxu** [comment]
Use `WhichKeyFloating`.
