### ISSUE TITLE
Neovim exits on timeout

### ISSUE THREAD

**Issue by ovidius72** [liuchengxu/vim-which-key#78]
- OS: Mac OSX 10.13.3

- Vim: Nvim 0.5.0-dev

Mapping which-key as following:
`nnoremap <silent> <leader> :WhichKey '<Space>'<CR>`

If i click <Leader> (space bar) and do not press any other button within the `timeoutlen` time neovim exits.

the output of messages is the following:

`
Errore/i eseguendo function which_key#start[54]..which_key#window#open[31]..which_key#window#fill[24]..which_key#wait_for_input
[17]..<SNR>223_handle_input[16]..which_key#wait_for_input[17]..<SNR>223_handle_input[16]..which_key#wait_for_input[17]..<SNR>22
3_handle_input[16]..which_key#wait_for_input[17]..<SNR>223_handle_input[16]..which_key#wait_for_input[10]..<SNR>223_getchar[38]
..which_key#util#parse_getchar:                                                                                                
riga    6:                                                                                                                     
E716: Chiave assente dal Dizionario: <80><fd>,                                                                                 
E15: Espressione non valida: g:which_key#util#special_keys[a:input]                                                            
Errore/i eseguendo function which_key#start[54]..which_key#window#open[31]..which_key#window#fill[24]..which_key#wait_for_input
[17]..<SNR>223_handle_input[16]..which_key#wait_for_input[17]..<SNR>223_handle_input[16]..which_key#wait_for_input[17]..<SNR>22
3_handle_input[16]..which_key#wait_for_input[17]..<SNR>223_handle_input[16]..which_key#wait_for_input[17]..<SNR>223_handle_inpu
t[16]..which_key#wait_for_input[10]..<SNR>223_getchar[38]..which_key#util#parse_getchar:                                       
riga    6:                                                                                                                     
E716: Chiave assente dal Dizionario: <80><fd>.                                                                                 
E15: Espressione non valida: g:which_key#util#special_keys[a:input]    
`

**Comment by liuchengxu** [comment]
Can't reproduce.

**Comment by ovidius72** [comment]
The cause should be some other plugin. I've tried the same setup in another PC with the same result.
Disabling all the plugins the issue's gone. I will try to found out what is the plugin responsible of this issue.  Thanks

**Comment by ovidius72** [comment]
Sorry to bother you again reopening an old issue, but I've found that the problem occurs when you have NerdTree or coc-explorer open and you press the Leader key to show up the Which-Key window. Is there anything I can do to avoid this ?
Thanks.

**Comment by liuchengxu** [comment]
I can't reproduce, so can't help more.

**Comment by ovidius72** [comment]
Thanks. I already have the latest code but still facing this issue. I will try to figure out why this happens.
