### ISSUE TITLE
Which key reduces the size of the buffer when there's a floating window

### ISSUE THREAD

**Issue by gquittet** [liuchengxu/vim-which-key#81]
- OS: macOS 10.15.1

- Vim: neovim v0.4.3

### Problem Description

When I press `<ESC>` to close `which key` and `neovim` is showing a popup at the same time, the buffer size comes really small.

#### How to reproduce

1. Show a popup
2. Trigger `which key`
3. Press the escape key `<ESC>`
4. The buffer has now the size of the popup

#### Pictures 

![image](https://user-images.githubusercontent.com/11082739/70896976-084c8280-1ff2-11ea-9f94-a2816a42dd59.png)

![image](https://user-images.githubusercontent.com/11082739/70897260-8f015f80-1ff2-11ea-9f10-dcc24b9200a8.png)

![image](https://user-images.githubusercontent.com/11082739/70897000-14d0db00-1ff2-11ea-8462-3cc3554cddd8.png)

**Comment by liuchengxu** [comment]
Please provide the minimal vimrc and detailed steps to reproduce. Otherwise I think it's more like a neovim issue.

**Comment by gquittet** [comment]
I've only this issue with `coc.nvim` floating windows so I think it's related with this extension. I will open an extension on their side.

**Comment by gquittet** [comment]
Linked `coc.nvim` issue: https://github.com/neoclide/coc.nvim/issues/1407

**Comment by gquittet** [comment]
I've found a workaround that fix the issue.
Here is the link of this workaround: https://github.com/neoclide/coc.nvim/issues/1407#issuecomment-566438921
