### ISSUE TITLE
Feature Request: make gap between floating window and command line optional

### ISSUE THREAD

**Issue by davidsierradz** [liuchengxu/vim-which-key#82]
- OS: Linux

- Vim: NVIM v0.5.0-242-g473aea92c

### Problem Description

With: 

```diff
diff --git a/autoload/which_key/window.vim b/autoload/which_key/window.vim
index ecf4106..5840632 100644
--- a/autoload/which_key/window.vim
+++ b/autoload/which_key/window.vim
@@ -109,7 +109,7 @@ function! s:show_floating_win(rows, layout) abort
         \ win_getid(s:winnr),
         \ {
         \   'relative': 'editor',
-        \   'row': &lines - nvim_buf_line_count(s:bufnr) - &cmdheight - 1,
+        \   'row': &lines - nvim_buf_line_count(s:bufnr) - &cmdheight,
         \   'col': 0,
         \   'width': &columns,
         \   'height': a:layout.win_dim + 2
```

Before opening:

![1](https://user-images.githubusercontent.com/9190258/71125745-8907ac00-21b5-11ea-8a47-c5c3796df33d.png)

Without change (notice the gap):

![2](https://user-images.githubusercontent.com/9190258/71125746-8907ac00-21b5-11ea-930c-4695f3f9f256.png)

After the change:

![3](https://user-images.githubusercontent.com/9190258/71125744-8907ac00-21b5-11ea-9ad0-b9bfff9d9c15.png)

Thanks!

Edit: So, this happens only with:

```vimscript
autocmd! FileType which_key
autocmd  FileType which_key set laststatus=0 noshowmode noruler
      \| autocmd BufLeave <buffer> set laststatus=2
```

**Comment by liuchengxu** [comment]
Try adding this option, see `:h g:which_key_floating_opts`.

```vim
let g:which_key_floating_opts = { 'row': '-1' }
```

**Comment by davidsierradz** [comment]
Thanks!, for some reason the correct one is `let g:which_key_floating_opts = { 'row': '+1', 'width': '100' }` , I need to explicitly set the width or:

![pic-selected-191219-1909-12](https://user-images.githubusercontent.com/9190258/71219471-22f15680-2293-11ea-88ea-c0acedfa9616.png)

(Notice the gap in left side `~`)

**Comment by liuchengxu** [comment]
You are actually increasing the width by 64, the code is not desiged for the absolute width, see https://github.com/liuchengxu/vim-which-key/commit/c2911983ce1352c2feebe22043d4abc10b0e9e34#diff-cb05767c2c7006a17dfd0609c8cd399eR68, `:echo eval("0"."100")`. If you want to to more fine-grained floating_win layout, you basically have to figure it out how it works with `row`, `col`, `width`, `height` on your own, `:h nvim_open_win()`.

**Comment by davidsierradz** [comment]
yeah my bad, should be `let g:which_key_floating_opts = { 'row': '+1', 'width': '+1' }`

thanks!
