### ISSUE TITLE
Which-key broke vim-airline statusline highlight

### ISSUE THREAD

**Issue by tuberry** [liuchengxu/vim-which-key#84]
- OS: ArchLinux

- Vim: 8.1.2268

If you think it's a bug, please provide a minimal vimrc to reproduce:

```vim
let mapleader = ','
call plug#begin('~/.vim/plugged')
Plug 'vim-airline/vim-airline'
Plug 'liuchengxu/vim-which-key'
Plug 'hecal3/vim-leader-guide'
call plug#end()              
```

### Problem Description

[Vim-airline](https://github.com/vim-airline/vim-airline)'s statusline highlight has lost after calling `:WhichKey '<leader>'`, which is restored correctly with [leader-guide](https://github.com/hecal3/vim-leader-guide)

Before:
![wkbefore](https://user-images.githubusercontent.com/17917040/71582355-cd476480-2b44-11ea-8093-af3630bad152.png)
After:
![wkafter](https://user-images.githubusercontent.com/17917040/71582361-d2a4af00-2b44-11ea-8b94-a861e91cfcb7.png)

**Comment by liuchengxu** [comment]
Please provide a **complete** yet minimal vimrc to help reproduce. The minimal vimrc you provided is obviouly incomplete.

**Comment by tuberry** [comment]
> Please provide a **complete** yet minimal vimrc to help reproduce. The minimal vimrc you provided is obviouly incomplete.

Sorry for my negligence, I updated the vimrc and screenshots just now.
