### ISSUE TITLE
Popup menu skews right in vertical split window when number is on 

### ISSUE THREAD

**Issue by tuberry** [liuchengxu/vim-which-key#86]
- OS: ArchLinux

- Vim:  8.1.2268

If you think it's a bug, please provide a minimal vimrc to reproduce:

```vim
set number
call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vim-which-key'
call plug#end()
map ,a test-test
map ,b test-test
map ,c test-test
map ,d test-test
map ,e test-test
map ,f test-test
map ,g test-test
map ,h test-test
```

### Problem Description
1. Edit two files with `vim -O a b`;
2. Call `:WhichKey ','`  

![vimskew](https://user-images.githubusercontent.com/17917040/71640201-68b11480-2cc0-11ea-934e-12bfa5675f02.png)

**Comment by liuchengxu** [comment]
Can not reproduce.

**Comment by tuberry** [comment]
![vwkskew](https://user-images.githubusercontent.com/17917040/71736468-13c1f980-2e8c-11ea-808a-5728c7afaa60.png)
The popup doesn't cover the numbers and looks like skewed. It seems that which-key limits the popup in one window.

**Comment by bsander** [comment]
I think I have a similar misalignment issue, though it happens even without splits.

https://github.com/liuchengxu/vim-which-key/blob/f8dba6aa812eb65cc4a33b2463174a4d155c6a02/autoload/which_key/window.vim#L111
Somehow, here `strlen(string(line('$')))` returns 3 for me. 

<img width="1278" alt="Screenshot 2020-01-04 at 18 50 26" src="https://user-images.githubusercontent.com/517850/71769542-1d4a7080-2f23-11ea-99b8-4685358ad95d.png">

**Comment by linjiX** [comment]
I also met the similar issue，
As @tuberry said, seems the popup window is limited in one window
Here is the snapshot:
- WhichKey in normal situation：
![normal](https://user-images.githubusercontent.com/46097255/72779905-49226180-3c58-11ea-814d-02d2e2511520.png)
- WhichKey in vsplit situation:
![vsplit](https://user-images.githubusercontent.com/46097255/72779906-49226180-3c58-11ea-8085-ae0c2ed6abb5.png)

**Comment by brglng** [comment]
I have a similar issue here.

![图片](https://user-images.githubusercontent.com/1525226/73954756-405eaa80-493d-11ea-9ce6-004fb396c46e.png)

**Comment by liuchengxu** [comment]
@linjiX @brglng Try #98, it's likely a regression of the new option `g:which_key_floating_relative_win` for opening the floating relative to the starting window,

**Comment by linjiX** [comment]
I did a simple test for #98 and it works：

<img width="1440" alt="截屏2020-02-14下午12 06 56" src="https://user-images.githubusercontent.com/46097255/74500760-e5234e00-4f22-11ea-9d58-8a1893578ff7.png">

Thanks~

**Comment by brglng** [comment]
@liuchengxu It looks like the appearance is ok, but the key descriptions do not show correctly.

![图片](https://user-images.githubusercontent.com/1525226/74505622-9bdafa80-4f32-11ea-8393-17b6b0e9c498.png)

**Comment by brglng** [comment]
@liuchengxu Sorry. I just did a restart and there is no problem now.

**Comment by brglng** [comment]
There is still a minor issue here.

When vista.vim's window is open, which-key's window shows different width when the leader key is pressed under vista's window and under normal buffer window.

This is the screenshot when pressed under vista's window:
![图片](https://user-images.githubusercontent.com/1525226/74506584-fbd2a080-4f34-11ea-93ba-056c84336bf7.png)

And this is the screenshot when pressed under normal buffer window:
![图片](https://user-images.githubusercontent.com/1525226/74506621-16a51500-4f35-11ea-8286-6645f144c049.png)

**Comment by liuchengxu** [comment]
File a new issue with detailed report if you find a new problem. @brglng

**Comment by brglng** [comment]
@liuchengxu Should I create a new issue for the problem I mentioned in https://github.com/liuchengxu/vim-which-key/issues/86#issuecomment-586116064 ?

**Comment by tuberry** [comment]
The skew vanished but a gap occurs. Plz fix it, thanks.
![image](https://user-images.githubusercontent.com/17917040/76412697-0155c600-63cf-11ea-87f5-8d995b45a721.png)

![image](https://user-images.githubusercontent.com/17917040/76412792-3a8e3600-63cf-11ea-9781-5710b2df25be.png)
