### ISSUE TITLE
A popup message whenever vim starts

### ISSUE THREAD

**Issue by hongyuanjia** [liuchengxu/vim-which-key#88]
- OS: Windows 10

- Vim: Vim 8.1.2333

### Problem Description
```vim
" Use space as leader key
let g:mapleader = "\<Space>"

" Use comma as local leader key
let g:maplocalleader = ','

" Use which-key
autocmd! User vim-which-key call which_key#register('<Space>', 'g:which_key_map')
nnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>
vnoremap <silent> <leader>      :<c-u>WhichKeyVisual '<Space>'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey  ','<CR>
vnoremap <silent> <localleader> :<c-u>WhichKeyVisual ','<CR>

" Define prefix dictionary
let g:which_key_map =  {}

" Other key bindings
...
```

Not sure why, but whenever I start vim, this message pops up. I can get rid of it if I remove all `let g:which_key_map` things. Below is the screen shot:

![image](https://user-images.githubusercontent.com/20545387/71674376-fc184180-2db5-11ea-84bd-5ad1dd88d360.png)

Any insight?

**Comment by liuchengxu** [comment]
Should be an issue of your own vimrc. Try commenting out the unrelated stuff in your vimrc to find the culprit.

**Comment by hongyuanjia** [comment]
Sorry for the bother. Indeed it is caused by own vimrc...
