### ISSUE TITLE
It looks like if the columns is not enough to display which_key prompt, vim will quit automatically.

### ISSUE THREAD

**Issue by Freed-Wu** [liuchengxu/vim-which-key#89]
OS: Windows10
vim: vim 8.1&gvim 8.1

If columns is too small to display which_key prompt, vim or gvim will quit automatically.
It is not a serious problem because user usually don't define too long map. But some plugin developer maybe do. for example

![Image 6](https://user-images.githubusercontent.com/32936898/71709924-c5cdd700-2e34-11ea-808d-e30994b256cc.png)
 
Thank you!

**Comment by liuchengxu** [comment]
Can not reproduce.

**Comment by linjiX** [comment]
I met the same issue on macOS.
According to my test, this bug only happens in neovim.
Here is a mini reproduce vimrc:
```
set nocompatible

call plug#begin('~/.vim/plug')
Plug 'liuchengxu/vim-which-key'
call plug#end()

let g:which_key_use_floating_win = 1

nnoremap ,t :long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-long-command
nnoremap , :WhichKey ','<CR>
```
Press `,` will make neovim quit automatically.
Hope it helps.

**Comment by matteoeghirotta** [comment]
can confirm the problem with neovim 0.4.3 on macOS catalina. Quite annoying since it quits editing in the middle of typing, losing all changes since last save. Had to disable the plugin.

**Comment by ovidius72** [comment]
So probably this is the same problem I'm having as described [here](https://github.com/liuchengxu/vim-which-key/issues/78)
