### ISSUE TITLE
键

### ISSUE THREAD

**Issue by 178me** [liuchengxu/vim-which-key#91]
我使用neovim无法用<leader>键呼出它。。。可以使用命令打开，但是我的描述并没有显示出来。原生版的vim可以呼出但是也无法显示内容如
![UTOOLS1578495141072.png](https://img03.sogoucdn.com/app/a/100520146/06c9a0ef69cbca494c776e5fe768831f)
![UTOOLS1578495566588.png](https://img01.sogoucdn.com/app/a/100520146/60fa832cd19b0f8b5ae24b45352bbedb)

**Comment by liuchengxu** [comment]
>If you think it's a bug, please provide a minimal vimrc to reproduce:

**Comment by 178me** [comment]
我的neovim配置文件就只有这些了，解决了呼出的问题，但是dict还是没有显示出来
![e450914df8b5a1fe98332cca03d5f1e2.png](http://yanxuan.nosdn.127.net/f8188318a09a8111e7a49e6b895e5edd.png)
图片备用:http://yanxuan.nosdn.127.net/f8188318a09a8111e7a49e6b895e5edd.png
