### ISSUE TITLE
dark mode for plugin?

### ISSUE THREAD

**Issue by woshichuanqilz** [liuchengxu/vim-which-key#94]
I use `seoul 256` color theme,  dark version. 

When I use vim-which-key, it open the pop up window like this which is hard to recognize the word in it. So how to change it, any dark version theme already set ? 

Thx in advance.

![无标题](https://user-images.githubusercontent.com/11295355/73133298-aefc5800-4061-11ea-9416-ca7afc8f4d93.png)

**Comment by liuchengxu** [comment]
https://github.com/liuchengxu/vim-which-key/issues/58#issuecomment-509653809

**Comment by woshichuanqilz** [comment]
already added but seems some conflict in the color scheme any way to solve it? 

![](https://raw.githubusercontent.com/woshichuanqilz/origamiimage/master/20200127115138.png)
