### ISSUE TITLE
相同键名的对象合并在同一菜单中显示

### ISSUE THREAD

**Issue by PetrusZ** [liuchengxu/vim-which-key#97]
![image](https://user-images.githubusercontent.com/4990592/74050525-39a16780-4a11-11ea-8d6f-6ed286c1a020.png)
![image](https://user-images.githubusercontent.com/4990592/74050564-4f169180-4a11-11ea-860b-ecf70edd5c82.png)
可以将这两个合并在一起显示吗？

例如希望显示成这样：
```
d-> +diagnostics
d -> CocList diagnostics
<space> n +Coc
```
现在如果配置为：
```
let g:which_key_map['nd'] = [':CocList diagnostics', 'CocList diagnostics']
let g:which_key_map.n =  {
            \ 'name' : '+CoC',
            \ 'd'    :  {
                \ 'name' : '+diagnostic',
                \ 'p'    :  ['<Plug>(coc-diagnostic-prev)', 'next-diagnostic'],
                \ 'n'    :  ['<Plug>(coc-diagnostic-next)', 'previous-diagnostic'],
              \ }
            \ }
```
![image](https://user-images.githubusercontent.com/4990592/74051760-8c7c1e80-4a13-11ea-8da5-dd176f12829c.png)
则`nd`不会出现在`n->+CoC`中，而是两者并列在一起出现。

**Comment by PetrusZ** [comment]
试了下上面的配置，`let g:which_key_map['nd'] = ['CocList diagnostics', 'CocList diagnostics']`，nd还无法正常执行`:CocList diagnositcs`命令

**Comment by liuchengxu** [comment]
**Warning: if you don't fill this issue template and provide the reproducible steps the issue could be closed directly.**

**Comment by PetrusZ** [comment]
- OS:gentoo
 - (Neo)Vim version: 8.2
 - vim-which-key version: lastest
 - Have you reproduced with a minimal vimrc: Yes

**Describe the bug**
```

**To Reproduce**
Steps to reproduce the behavior:

1. Create the minimal vimrc `min.vim`:

```vim
set nocompatible
set runtimepath^=/path/to/vim-which-key
syntax on
filetype plugin indent on
```

2. Start (neo)vim with command: `vim -u min.vim`

3. Type '....'

4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Additional context**
Add any other context about the problem here.

**Comment by PetrusZ** [comment]
- OS:gentoo
 - (Neo)Vim version: 8.2
 - vim-which-key version: lastest
 - Have you reproduced with a minimal vimrc: Yes

**Describe the bug**
![image](https://user-images.githubusercontent.com/4990592/74080307-ace0c300-4a7d-11ea-87a6-20bde2fe144a.png)
`nd`不在`n-> test`中

![image](https://user-images.githubusercontent.com/4990592/74080323-d699ea00-4a7d-11ea-8623-dabda2850932.png)
`ac`, `qf`, `rn` 无效

**To Reproduce**

minimal vimrc
```
set nocompatible
set runtimepath^=/home/petrus/.vim/plugged/vim-which-key
syntax on
filetype plugin indent on

let g:mapleader="\<space>"

call which_key#register('<Space>', 'g:which_key_map')

" Define prefix dictionary
let g:which_key_map =  {}

let g:which_key_map['nd'] = [':echo "nd"', 'nd']
let g:which_key_map.n =  {
            \ 'name' : '+test',
            \ 'rn'   :  [':echo "rn"', 'rn'],
            \ 'ac'   :  [':echo "ac"', 'ac'],
            \ 'qf'   :  [':echo "qf"', 'af'],
            \ 'd'    :  {
                \ 'name' : '+test_test',
                \ 'p'    :  [':echo "dp"', 'dp'],
                \ 'n'    :  [':echo "dn"', 'dn'],
              \ }
            \ }

let g:which_key_exit = ["\<C-c>", "\<Esc>"]

nnoremap <silent> <leader> :<c-u>WhichKey '<Space>'<CR>
vnoremap <silent> <leader> :<c-u>WhichKeyVisual '<Space>'<CR>
```

Type: `<leader>ac`, `<leader>qf`, `<leader>rn` 无效

**Expected behavior**
```
<leader>ac -> echo ac
<leader>qf -> echo qf
<leader>ac -> echo rn
```
还有`nd`在`n-> test`菜单中

**Comment by liuchengxu** [comment]
你自己的用法有问题，不要同时有 `nd`, 又同时给 `nd` 分级。

**Comment by PetrusZ** [comment]
`<leader>nac`, `<leader>nqf`, `<leader>nrn` 也都无效，还有Visual下不能正常工作的问题。添加配置：
```
let g:which_key_map.n =  {
            \ 'f'   :   ['=', 'format'],
}
```

Visual模式下，`<leader>nf`先后图中无任何变化
![image](https://user-images.githubusercontent.com/4990592/74080730-1c58b180-4a82-11ea-893f-77ba25af8755.png)

**Comment by PetrusZ** [comment]
`<leader>me`无法忽略，添加配置：
```
`nmap <leader>me :echo "me"<CR>`
let g:which_key_map.m = {
            \ 'e' : 'which_key_ignore'
            \ }
```

键入`<leader>me'，结果如图：

![image](https://user-images.githubusercontent.com/4990592/74081788-d30e5f00-4a8d-11ea-8026-fc62afbcf03c.png)
![image](https://user-images.githubusercontent.com/4990592/74081792-dc97c700-4a8d-11ea-8d85-6447e212c246.png)

`me`已为空，但`m`菜单还是存在。

如果配置为：
```

**Comment by PetrusZ** [comment]
https://github.com/liuchengxu/vim-which-key/issues/97#issuecomment-583709710

**Comment by PetrusZ** [comment]
https://github.com/liuchengxu/vim-which-key/issues/97#issuecomment-583709710
https://github.com/liuchengxu/vim-which-key/issues/97#issuecomment-583714919
都无法修复？还是什么问题？
