### ISSUE TITLE
Lazy load cause cursor jump around

### ISSUE THREAD

**Issue by PetrusZ** [liuchengxu/vim-which-key#99]
**Environment (please complete the following information):**
 - OS: gentoo
 - (Neo)Vim version: 8.2
 - Have you reproduced with a minimal vimrc: yes

**Describe the bug**
When using vim-plug lazy load for vim-which-key, and cursor will jump around when you first time and vim and type `<space>`

**To Reproduce**
Open vim, move cursor to Where needed, then type `<space>`, you will see cursor jump back to where it start.

**Expected behavior**
Use vim-plug lazy load vim-which-key, and keep cursor stay in put.

**Comment by liuchengxu** [comment]
Can't reproduce with the following vimrc:

```vim
set nocp

call plug#begin('~/.vim/plugged')
Plug 'liuchengxu/vim-which-key'
call plug#end()

let g:mapleader = "\<Space>"
let g:maplocalleader = ','

nnoremap <silent> <leader>      :<c-u>WhichKey '<Space>'<CR>
nnoremap <silent> <localleader> :<c-u>WhichKey  ','<CR>

let g:which_key_map =  {}

nnoremap <leader><CR> :buffer#<CR>

call which_key#register('<Space>', "g:which_key_map")
```

Based on my experience, this hook https://github.com/liuchengxu/space-vim/blob/master/layers/%2Bdistributions/spacevim/config.vim#L4-L9 can result in this issue.
